### ISSUE TITLE
0.1.1 errors after update

### ISSUE THREAD

**Issue by a-sk** [proofit404/anaconda-mode#104]
Hello.

I use spacemacs.
Just updated the anaconda package.

These are errors I get:

```
eldoc error: (error 127.0.0.1%3anil/80 nodename nor servname provided, or not known)
error in process sentinel: apply: Setting current directory: no such file or directory, /Users/askurihin/.emacs.d/anaconda-mode/0.1.1
error in process sentinel: Setting current directory: no such file or directory, /Users/askurihin/.emacs.d/anaconda-mode/0.1.1
```

**Comment by proofit404** [comment]
Could you provide `*anaconda-mode*` buffer content?

**Comment by a-sk** [comment]
It's actually empty:

<img width="632" alt="anaconda-buffer-is-empty" src="https://cloud.githubusercontent.com/assets/53479/9714684/2332677c-5562-11e5-929b-4c3fa129ccd7.png">

**Comment by nixmaniack** [comment]
I am facing the same problem since the upgrade. `*anaconda-mode*` buffer is empty. Following is the backtrace generated.

```
Debugger entered--Lisp error: (file-error "Setting current directory" "no such file or directory" "/home/nixmaniack/.emacs.d/anaconda-mode/0.1.1")
  start-process("anaconda-mode" "*anaconda-mode*" "ipython" "-c" "\n
from pkg_resources import get_distribution\n
def check_deps(deps=['anaconda_mode']):\n
    for each in deps:\n
        distrib = get_distribution(each)\n
        requirements = distrib.requires()\n
        check_deps(requirements)\n
check_deps()\n
")
  apply(start-process "anaconda-mode" "*anaconda-mode*" "ipython" ("-c" "\n
from pkg_resources import get_distribution\n
def check_deps(deps=['anaconda_mode']):\n
    for each in deps:\n
        distrib = get_distribution(each)\n
        requirements = distrib.requires()\n
        check_deps(requirements)\n
check_deps()\n
"))
  start-file-process("anaconda-mode" "*anaconda-mode*" "ipython" "-c" "\n
from pkg_resources import get_distribution\n
def check_deps(deps=['anaconda_mode']):\n
    for each in deps:\n
        distrib = get_distribution(each)\n
        requirements = distrib.requires()\n
        check_deps(requirements)\n
check_deps()\n
")
  apply(start-file-process "anaconda-mode" "*anaconda-mode*" "ipython" ("-c" "\n
from pkg_resources import get_distribution\n
def check_deps(deps=['anaconda_mode']):\n
    for each in deps:\n
        distrib = get_distribution(each)\n
        requirements = distrib.requires()\n
        check_deps(requirements)\n
check_deps()\n
"))
  start-pythonic(:process "anaconda-mode" :buffer "*anaconda-mode*" :cwd "/home/nixmaniack/.emacs.d/anaconda-mode/0.1.1" :sentinel #[514 "\301\300#\207" [#[0 "\302\300\301\"\207" ["eldoc" anaconda-mode-eldoc-callback anaconda-mode-jsonrpc] 3 "\n
\n
(fn)"] anaconda-mode-check-sentinel] 6 "\n
\n
(fn PROCESS EVENT)"] :args ("-c" "\n
from pkg_resources import get_distribution\n
def check_deps(deps=['anaconda_mode']):\n
    for each in deps:\n
        distrib = get_distribution(each)\n
        requirements = distrib.requires()\n
        check_deps(requirements)\n
check_deps()\n
"))
  anaconda-mode-check(#[0 "\302\300\301\"\207" ["eldoc" anaconda-mode-eldoc-callback anaconda-mode-jsonrpc] 3 "\n
\n
(fn)"])
  anaconda-mode-ensure-directory-sentinel(#<process anaconda-mode> "finished\n
" #[0 "\302\300\301\"\207" ["eldoc" anaconda-mode-eldoc-callback anaconda-mode-jsonrpc] 3 "\n
\n
(fn)"])
  #[514 "\301\300#\207" [#[0 "\302\300\301\"\207" ["eldoc" anaconda-mode-eldoc-callback anaconda-mode-jsonrpc] 3 "\n
\n
(fn)"] anaconda-mode-ensure-directory-sentinel] 6 "\n
\n
(fn PROCESS EVENT)"](#<process anaconda-mode> "finished\n
")
```

I also noticed `-c` directory created in `~/` if it helps anywhere!
Let me know if I can provide anything for more debugging.

**Comment by signalpillar** [comment]
Facing the same problem =( . I use spacemacs too

**Comment by proofit404** [comment]
Does changing `python-shell-interpreter` to `nil` solve this problem?

**Comment by cpaulik** [comment]
In spacemacs the `python-shell-interpreter` is set to `ipython` if it is installed.

Setting it back to `python` fixed the problem for me.

**Comment by cpaulik** [comment]
Switching to a virtualenv also installed the `anaconda-mode` folder even when the virtualenv had `ìpython` installed.

I can also confirm the `-c` folder in my home directory.

**Comment by synic** [comment]
How are you setting it?  In spacemacs, having the following in my `user-config`:

```lisp
(setq python-shell-interpreter 'python)
```

does *not* fix the problem for me

**Comment by nixmaniack** [comment]
@proofit404 Setting `python-shell-interpreter` to `python` did solve the issue. Although I had to do `(setq anaconda-mode-server-script "/usr/local/lib/python2.7/dist-packages/anaconda_mode.py")` as well before getting completion working.  

@cpaulik I do use spacemacs. Thanks for the fix!

**Comment by lunaryorn** [comment]
I would not say that this is a “fix”.  It's a workaround, and I'd pretty much prefer to be able to use `ipython` in Emacs without breaking Anaconda Mode :unamused:

**Comment by cpaulik** [comment]
@lunaryorn yes I fully agree

**Comment by proofit404** [comment]
@lunaryorn @cpaulik fix in the progress.

**Comment by lunaryorn** [comment]
@proofit404 Thank you very much :)

**Comment by proofit404** [comment]
Please check last master updates.

**Comment by nixmaniack** [comment]
Tried master. Still getting this.

```
Debugger entered--Lisp error: (error "127.0.0.1%3anil/80 Name or service not known")
  make-network-process(:name "127.0.0.1%3anil" :buffer #<buffer  *url-http-temp*> :host "127.0.0.1%3anil" :service 80 :nowait t)
  open-network-stream("127.0.0.1%3anil" #<buffer  *url-http-temp*> "127.0.0.1%3anil" 80 :type plain :nowait t)
  byte-code("\306\211^X^Y\n\307>\203$^@\n\310=\203^R^@\311^R\312^K\f^M^N^X\313\n\314\315\316\317\"&^H\202Y^@\n\320=\2034^@\321^K\f^M^N^X$\202Y^@\n\322$
  url-open-stream("127.0.0.1%3anil" #<buffer  *url-http-temp*> "127.0.0.1%3anil" 80)
  url-http-find-free-connection("127.0.0.1%3anil" 80)
  url-http([cl-struct-url "http" nil nil "127.0.0.1%3anil" nil "/" nil nil t t t] (closure ((anaconda-mode-request-tick . 1) (anaconda-mode-request-wi$
  url-retrieve-internal("http://127.0.0.1:nil" (closure ((anaconda-mode-request-tick . 1) (anaconda-mode-request-window . #<window 1 on main.py>) (ana$
  url-retrieve("http://127.0.0.1:nil" (closure ((anaconda-mode-request-tick . 1) (anaconda-mode-request-window . #<window 1 on main.py>) (anaconda-mod$
  (let ((url-request-method "POST") (url-request-data (anaconda-mode-jsonrpc-request command))) (url-retrieve (format "http://%s:%s" (anaconda-mode-ho$
  anaconda-mode-jsonrpc("eldoc" anaconda-mode-eldoc-callback)
  (closure ((callback . anaconda-mode-eldoc-callback) (command . "eldoc") t) nil (anaconda-mode-jsonrpc command callback))()
  funcall((closure ((callback . anaconda-mode-eldoc-callback) (command . "eldoc") t) nil (anaconda-mode-jsonrpc command callback)))
  (progn (funcall callback))
  (if callback (progn (funcall callback)))
  (if (anaconda-mode-running-p) (if callback (progn (funcall callback))) (anaconda-mode-ensure-directory callback))
  anaconda-mode-start((closure ((callback . anaconda-mode-eldoc-callback) (command . "eldoc") t) nil (anaconda-mode-jsonrpc command callback)))
  anaconda-mode-call("eldoc" anaconda-mode-eldoc-callback)
  anaconda-mode-eldoc-function()
  #[0 "\302 \204^O^@^H\205G^@\303\304!\210\304\207  \203^X^@\303   !\207\305 \306 \211\204$^@\304\202B^@^A^A@=\2038^@\307\310^B\"\206B^@\311^B!\202B^@$
  funcall(#[0 "\302 \204^O^@^H\205G^@\303\304!\210\304\207  \203^X^@\303   !\207\305 \306 \211\204$^@\304\202B^@^A^A@=\2038^@\307\310^B\"\206B^@\311^B$
  eldoc-print-current-symbol-info()
  #[0 "^H\205^F^@\301 \207" [eldoc-mode eldoc-print-current-symbol-info] 1 "\n\n(fn)"]()
  apply(#[0 "^H\205^F^@\301 \207" [eldoc-mode eldoc-print-current-symbol-info] 1 "\n\n(fn)"] nil)
  byte-code("r\301^H\302H^H\303H\"\210)\301\207" [timer apply 5 6] 4)
  timer-event-handler([t 0 0 500000 t #[0 "^H\205^F^@\301 \207" [eldoc-mode eldoc-print-current-symbol-info] 1 "\n\n(fn)"] nil idle 0])
```

**Comment by beardedprojamz** [comment]
I have latest master now - after blowing out my `.emacs.d/elpa` in spacemacs, and things seem to be back to normal for me.

**Comment by cpaulik** [comment]
I installed the latest MELPA package and I still have errors in the `*anaconda-mode*` buffer:

```
[1;31mDistributionNotFound[0m: anaconda-mode
[TerminalIPythonApp] WARNING | File not found: u'anaconda_mode.py'
[1;31m---------------------------------------------------------------------------[0m
[1;31mDistributionNotFound[0m                      Traceback (most recent call last)
[1;32m<ipython-input-1-b5fda19feb15>[0m in [0;36m<module>[1;34m()[0m
[0;32m      6[0m         [0mrequirements[0m [1;33m=[0m [0mdistrib[0m[1;33m.[0m[0mrequires[0m[1;33m([0m[1;33m)[0m[1;33m[0m[0m
[0;32m      7[0m         [0mcheck_deps[0m[1;33m([0m[0mrequirements[0m[1;33m)[0m[1;33m[0m[0m
[1;32m----> 8[1;33m [0mcheck_deps[0m[1;33m([0m[1;33m)[0m[1;33m[0m[0m
[0m
[1;32m<ipython-input-1-b5fda19feb15>[0m in [0;36mcheck_deps[1;34m(deps)[0m
[0;32m      3[0m [1;32mdef[0m [0mcheck_deps[0m[1;33m([0m[0mdeps[0m[1;33m=[0m[1;33m[[0m[1;34m'anaconda_mode'[0m[1;33m][0m[1;33m)[0m[1;33m:[0m[1;33m[0m[0m
[0;32m      4[0m     [1;32mfor[0m [0meach[0m [1;32min[0m [0mdeps[0m[1;33m:[0m[1;33m[0m[0m
[1;32m----> 5[1;33m         [0mdistrib[0m [1;33m=[0m [0mget_distribution[0m[1;33m([0m[0meach[0m[1;33m)[0m[1;33m[0m[0m
[0m[0;32m      6[0m         [0mrequirements[0m [1;33m=[0m [0mdistrib[0m[1;33m.[0m[0mrequires[0m[1;33m([0m[1;33m)[0m[1;33m[0m[0m
[0;32m      7[0m         [0mcheck_deps[0m[1;33m([0m[0mrequirements[0m[1;33m)[0m[1;33m[0m[0m

[1;32m/usr/local/lib/python2.7/dist-packages/pkg_resources.pyc[0m in [0;36mget_distribution[1;34m(dist)[0m
[0;32m    342[0m     [1;34m"""Return a current distribution object for a Requirement or string"""[0m[1;33m[0m[0m
[0;32m    343[0m     [1;32mif[0m [0misinstance[0m[1;33m([0m[0mdist[0m[1;33m,[0m[0mbasestring[0m[1;33m)[0m[1;33m:[0m [0mdist[0m [1;33m=[0m [0mRequirement[0m[1;33m.[0m[0mparse[0m[1;33m([0m[0mdist[0m[1;33m)[0m[1;33m[0m[0m
[1;32m--> 344[1;33m     [1;32mif[0m [0misinstance[0m[1;33m([0m[0mdist[0m[1;33m,[0m[0mRequirement[0m[1;33m)[0m[1;33m:[0m [0mdist[0m [1;33m=[0m [0mget_provider[0m[1;33m([0m[0mdist[0m[1;33m)[0m[1;33m[0m[0m
[0m[0;32m    345[0m     [1;32mif[0m [1;32mnot[0m [0misinstance[0m[1;33m([0m[0mdist[0m[1;33m,[0m[0mDistribution[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[0m
[0;32m    346[0m         [1;32mraise[0m [0mTypeError[0m[1;33m([0m[1;34m"Expected string, Requirement, or Distribution"[0m[1;33m,[0m [0mdist[0m[1;33m)[0m[1;33m[0m[0m

[1;32m/usr/local/lib/python2.7/dist-packages/pkg_resources.pyc[0m in [0;36mget_provider[1;34m(moduleOrReq)[0m
[0;32m    221[0m     [1;34m"""Return an IResourceProvider for the named module or requirement"""[0m[1;33m[0m[0m
[0;32m    222[0m     [1;32mif[0m [0misinstance[0m[1;33m([0m[0mmoduleOrReq[0m[1;33m,[0m[0mRequirement[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[0m
[1;32m--> 223[1;33m         [1;32mreturn[0m [0mworking_set[0m[1;33m.[0m[0mfind[0m[1;33m([0m[0mmoduleOrReq[0m[1;33m)[0m [1;32mor[0m [0mrequire[0m[1;33m([0m[0mstr[0m[1;33m([0m[0mmoduleOrReq[0m[1;33m)[0m[1;33m)[0m[1;33m[[0m[1;36m0[0m[1;33m][0m[1;33m[0m[0m
[0m[0;32m    224[0m     [1;32mtry[0m[1;33m:[0m[1;33m[0m[0m
[0;32m    225[0m         [0mmodule[0m [1;33m=[0m [0msys[0m[1;33m.[0m[0mmodules[0m[1;33m[[0m[0mmoduleOrReq[0m[1;33m][0m[1;33m[0m[0m

[1;32m/usr/local/lib/python2.7/dist-packages/pkg_resources.pyc[0m in [0;36mrequire[1;34m(self, *requirements)[0m
[0;32m    723[0m         [0mincluded[0m[1;33m,[0m [0meven[0m [1;32mif[0m [0mthey[0m [0mwere[0m [0malready[0m [0mactivated[0m [1;32min[0m [0mthis[0m [0mworking[0m [0mset[0m[1;33m.[0m[1;33m[0m[0m
[0;32m    724[0m         """
[1;32m--> 725[1;33m         [0mneeded[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0mresolve[0m[1;33m([0m[0mparse_requirements[0m[1;33m([0m[0mrequirements[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[0m
[0m[0;32m    726[0m [1;33m[0m[0m
[0;32m    727[0m         [1;32mfor[0m [0mdist[0m [1;32min[0m [0mneeded[0m[1;33m:[0m[1;33m[0m[0m

[1;32m/usr/local/lib/python2.7/dist-packages/pkg_resources.pyc[0m in [0;36mresolve[1;34m(self, requirements, env, installer, replace_conflicting)[0m
[0;32m    626[0m                         [1;31m# unfortunately, zc.buildout uses a str(err)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    627[0m                         [1;31m# to get the name of the distribution here..[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 628[1;33m                         [1;32mraise[0m [0mDistributionNotFound[0m[1;33m([0m[0mreq[0m[1;33m)[0m[1;33m[0m[0m
[0m[0;32m    629[0m                 [0mto_activate[0m[1;33m.[0m[0mappend[0m[1;33m([0m[0mdist[0m[1;33m)[0m[1;33m[0m[0m
[0;32m    630[0m             [1;32mif[0m [0mdist[0m [1;32mnot[0m [1;32min[0m [0mreq[0m[1;33m:[0m[1;33m[0m[0m

[1;31mDistributionNotFound[0m: anaconda-mode
[TerminalIPythonApp] WARNING | File not found: u'anaconda_mode.py'
Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "<string>", line 5, in check_deps
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 344, in get_distribution
    if isinstance(dist,Requirement): dist = get_provider(dist)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 223, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: anaconda-mode
Downloading/unpacking anaconda-mode==0.1.1
  Downloading anaconda_mode-0.1.1.tar.gz
  Running setup.py (path:/tmp/user/1000/pip_build_cp/anaconda-mode/setup.py) egg_info for package anaconda-mode
    
    no previously-included directories found matching 'test'
Downloading/unpacking jedi>=0.9.0 (from anaconda-mode==0.1.1)
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB): 
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):   2%  4.1kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):   5%  8.2kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):   7%  12kB 
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  10%  16kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  12%  20kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  15%  24kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  18%  28kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  20%  32kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  23%  36kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  25%  40kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  28%  45kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  31%  49kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  33%  53kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  36%  57kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  38%  61kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  41%  65kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  44%  69kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  46%  73kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  49%  77kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  51%  81kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  54%  86kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  57%  90kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  59%  94kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  62%  98kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  64%  102kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  67%  106kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  70%  110kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  72%  114kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  75%  118kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  77%  122kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  80%  126kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  83%  131kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  85%  135kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  88%  139kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  90%  143kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  93%  147kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  96%  151kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):  98%  155kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB): 100%  157kB
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB):            
  Downloading jedi-0.9.0-py2.py3-none-any.whl (157kB): 157kB downloaded
Downloading/unpacking service-factory>=0.1.2 (from anaconda-mode==0.1.1)
  Downloading service_factory-0.1.2.tar.gz
  Running setup.py (path:/tmp/user/1000/pip_build_cp/service-factory/setup.py) egg_info for package service-factory
    
Downloading/unpacking six (from service-factory>=0.1.2->anaconda-mode==0.1.1)
  Downloading six-1.9.0-py2.py3-none-any.whl
Installing collected packages: anaconda-mode, jedi, service-factory, six
  Running setup.py install for anaconda-mode
    
    no previously-included directories found matching 'test'
  Running setup.py install for service-factory
    
Successfully installed anaconda-mode jedi service-factory six
Cleaning up...
anaconda_mode port 9000
```

It works in the end in the above log because I changed the value of `python-shell-interpreter` to `python`

**Comment by proofit404** [comment]
@cpaulik Do you restart emacs after your upgrade? `DistributionNotFound` is expected error for the first run. If you doesn't restart emacs then `python-shell-interpretter` simply trigger server start.

Can you try to stop emacs, remove `~/.emacs.d/anaconda-mode` directory, and start emacs again?

**Comment by proofit404** [comment]
@nixmaniack Looks like anaconda-mode try to perform JSON-RPC request before server can bound port. I'll try to fix this tomorrow. Does this error persist on each command or only at the start of the work?

**Comment by nixmaniack** [comment]
@proofit404 On every command. 
Also I see following in `*anaconda-mode*` buffer.
```
[TerminalIPythonApp] WARNING | File not found: u'anaconda_mode.py'
```
I tried installing/uninstalling anaconda_mode through `pip`. I don't use virtualenv/pyenv. 
Doing this `(setq anaconda-mode-server-script "/usr/local/lib/python2.7/dist-packages/anaconda_mode.py")` fixes that error and completion works. But I assume we don't have to set it manually. 
Only setting server-script helped me, didn't have to change `python-shell-interpreter`, which indicates it worked with `ipython`.

**Comment by cpaulik** [comment]
@proofit404 yes I've restarted. In addition to the error in the `*anaconda-mode*` buffer I also get the following in `*Messages*`:

```
Company: An error occurred in auto-begin
127.0.0.1%3anil/80 Name or service not known
Company: An error occurred in auto-begin
127.0.0.1%3anil/80 Name or service not known
eldoc error: (error 127.0.0.1%3anil/80 Name or service not known)
```

Also the `anaconda-mode/0.1.1/` folder is created but nothing is installed into it.

**Comment by proofit404** [comment]
So finally I figure out exactly reason of this strange behavior. `ipython` always exit with zero status code even if exception was raised in the code block.
```shell
$ python -c 'import sys; sys.exit(1)'
$ echo $?
1
$ ipython -c 'import sys; sys.exit(1)'
An exception has occurred, use %tb to see the full traceback.

SystemExit: 1

To exit: use 'exit', 'quit', or Ctrl-D.
$ echo $?
0
```
Any one know the way to exit from `ipython` with non zero exit code?

**Comment by cpaulik** [comment]
@proofit404 Is this an option?

```shell
$ ipython -c "import os; os._exit(1)"
$ echo $?
1
```

**Comment by cpaulik** [comment]
@proofit404 With the latest changes, after update and deleting the `anaconda-mode` folder I now get the following at the end of the `anaconda-mode` buffer:

```
ipython nbconvert           # convert notebooks to/from other formats

[TerminalIPythonApp] CRITICAL | Bad config encountered during initialization:
[TerminalIPythonApp] CRITICAL | Unrecognized flag: '-t'
```

**Comment by proofit404** [comment]
Same result. IPython differ a lot from regular python. Will continue tomorrow :smile:

**Comment by a-sk** [comment]
Thanks, it works for me now.

**Comment by proofit404** [comment]
Glad we solve it.

**Comment by advancedxy** [comment]
Hi, I still had this problem. Looks like the anaconda-mode is not installed in ~/.emacs.d/cache. 
Running pip install -t . "anaconda-mode == 0.1.1" shows below:
```
Collecting anaconda-mode==0.1.1
Collecting jedi>=0.9.0 (from anaconda-mode==0.1.1)
  Using cached jedi-0.9.0-py2.py3-none-any.whl
Collecting service-factory>=0.1.2 (from anaconda-mode==0.1.1)
Collecting six (from service-factory>=0.1.2->anaconda-mode==0.1.1)
  Using cached six-1.9.0-py2.py3-none-any.whl
Installing collected packages: jedi, six, service-factory, anaconda-mode
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 646, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 803, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 998, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 242, in move_wheel_files
    name, user=user, home=home, root=root, isolated=isolated
  File "/usr/local/lib/python2.7/site-packages/pip/locations.py", line 192, in distutils_scheme
    i.finalize_options()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 264, in finalize_options
    "must supply either home or prefix/exec-prefix -- not both"
DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both
```
Using .pydistutils.cfg file mentioned by https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Homebrew-and-Python.md#note-on-pip-install---user, I can install anaconda-mode. The --install-prefix option won't work.

Hope this helps other people who still encounters this problem and you guys can find a way to fix this.

**Comment by synic** [comment]
Using Homebrew, that `~/.pydistutils.cfg` does indeed make `anacona-mode` able to install it's pip dependencies.  However, it breaks regular pip.

I was able to make it work by installing them manually.

I think the problem is that, by default, `pip install` on Linux *requires* a prefix if you aren't installing as root, where in Homebrew on OS X, it's already doing something to get around this.  You can `pip install "jedi>=0.9"` without root privileges.  Whatever homebrew is doing, it's not compatible with the `--prefix` that anaconda-mode is running.

**Comment by cpaulik** [comment]
I would see this as a clear bug in homebrewed Python since this breaks pip standard behavior. 

Anaconda mode is running `pip install -t . anaconda-mode=0.1.1` at the moment.

The `pip -t` option is clearly documented and states that this will install the packages in the given directory. This directory can be any directory and should have little to do with user vs. system Python.

**Comment by proofit404** [comment]
@cpaulik actually this is a `distutils` bug

**Comment by cpaulik** [comment]
Yeah I read that. But I wonder then how python distributions like anaconda can work around this. They don't seem to have this problem. Anyway I would recommend [Anaconda](https://www.continuum.io/downloads) or [miniconda](http://conda.pydata.org/miniconda.html) to any user for managing Python versions and installing packages, especially complicated ones like numpy or scipy.

**Comment by shwsun** [comment]
Hi, I know this issue is already closed, but I still came with this bug while using the newest Spacemacs. It looks like using .pydistutils.cfg file is the right approach to solve this problem.
