### ISSUE TITLE
jedi RPC error, anaconda-mode frozen the editor window

### ISSUE THREAD

**Issue by dzhwinter** [proofit404/anaconda-mode#112]
Error message:
```
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "IOError(2, \'No such file or directory\')"}}')
127.0.0.1 - - [12/Sep/2015 01:05:56] ================================================================================
Traceback (most recent call last):
  File "/tmp/pip-build-GlCYWH/service-factory/service_factory/providers/basehttp.py", line 40, in do_POST
  File "/tmp/pip-build-GlCYWH/service-factory/service_factory/service.py", line 49, in __call__
  File "/tmp/pip-build-GlCYWH/service-factory/service_factory/service.py", line 104, in apply
  File "/tmp/pip-build-GlCYWH/service-factory/service_factory/errors.py", line 92, in server_error
  File "/home/dzh/.emacs.d/anaconda-mode/0.1.1/six.py", line 692, in raise_from
    raise value


anaconda-mode     Version: 20150911.1146
jedi: INSTALLED: 0.9.0 (latest)
anaconda-mode install from pip 0.1.1
```

**Comment by proofit404** [comment]
Does `*anaconda-mode*` buffer contains port bound message? Why `service-factory` is installed into `tmp` directory?

**Comment by dzhwinter** [comment]
My issue was solved after i upgraded 'spacemacs'. Maybe it's caused by the wrong package install path.
this is all the message in anaconda-mode. no other messages, I have no idea why 'service-factory' show there.

**Comment by dzhwinter** [comment]
new error occur.

I post the '''anaconda-mode''' message buffer here.
'''
anaconda_mode port 9000
127.0.0.1 - - [13/Sep/2015 00:53:37] ================================================================================
Traceback (most recent call last):
  File "/home/dzh/.emacs.d/anaconda-mode/0.1.1/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/dzh/.emacs.d/anaconda-mode/0.1.1/service_factory/service.py", line 49, in __call__
    result = self.apply(method, args)
  File "/home/dzh/.emacs.d/anaconda-mode/0.1.1/service_factory/service.py", line 104, in apply
    server_error(args['id'], error)
  File "/home/dzh/.emacs.d/anaconda-mode/0.1.1/service_factory/errors.py", line 92, in server_error
    six.raise_from(ServiceException(500, dumps(response)), error)
  File "/home/dzh/.emacs.d/anaconda-mode/0.1.1/six.py", line 692, in raise_from
    raise value
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "KeyError(u\'mark\',)"}}')
127.0.0.1 - - [13/Sep/2015 00:53:45] ================================================================================
Traceback (most recent call last):
  File "/home/dzh/.emacs.d/anaconda-mode/0.1.1/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/dzh/.emacs.d/anaconda-mode/0.1.1/service_factory/service.py", line 49, in __call__
    result = self.apply(method, args)
  File "/home/dzh/.emacs.d/anaconda-mode/0.1.1/service_factory/service.py", line 104, in apply
    server_error(args['id'], error)
  File "/home/dzh/.emacs.d/anaconda-mode/0.1.1/service_factory/errors.py", line 92, in server_error
    six.raise_from(ServiceException(500, dumps(response)), error)
  File "/home/dzh/.emacs.d/anaconda-mode/0.1.1/six.py", line 692, in raise_from
    raise value
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "KeyError(u\'x\',)"}}')

'''

**Comment by proofit404** [comment]
Looks like actual exception is hidden by server error handler. Do you use python2?

**Comment by dzhwinter** [comment]
yes. my mainly workaround is _python 2.7.6_ . It works well for me before these days' big upgrading.

**Comment by proofit404** [comment]
Yes, python2 doesn't support `raise from` syntax used in the `service_factory` package. I suspect that the reason of your problems is new version of jedi library. Can you try following script from the interactive python shell opened at `~/.emacs.d/anaconda-mode/0.1.1`?
```python
import jedi
file_path = '/path/to/your/file.py'
jedi.Script(open(file_path).read(), <line number caused error>, <column number caused error>, file_path)
```

**Comment by proofit404** [comment]
Close due to inactivity.
