### ISSUE TITLE
OS X 10.8, python2.7 via Homebrew: "DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both"

### ISSUE THREAD

**Issue by apchamberlain** [proofit404/anaconda-mode#129]
I'm using OS X 10.8 and Emacs 24.3 compiled from source.  I have python2.7 installed via Homebrew.  When I try to start anaconda-mode, I get the following error in the `*anaconda-mode*` buffer:

```
Collecting anaconda-mode==0.1.1
  Using cached anaconda_mode-0.1.1.tar.gz
Collecting jedi>=0.9.0 (from anaconda-mode==0.1.1)
  Using cached jedi-0.9.0-py2.py3-none-any.whl
Collecting service-factory>=0.1.2 (from anaconda-mode==0.1.1)
  Using cached service_factory-0.1.2.tar.gz
Collecting six (from service-factory>=0.1.2->anaconda-mode==0.1.1)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six, service-factory, jedi, anaconda-mode
[31m  Exception:
  Traceback (most recent call last):
    File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/basecommand.py", line 232, in main
      status = self.run(options, args)
    File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/commands/install.py", line 347, in run
      root=options.root_path,
    File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/req/req_set.py", line 549, in install
      **kwargs
    File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/req/req_install.py", line 751, in install
      self.move_wheel_files(self.source_dir, root=root)
    File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/req/req_install.py", line 960, in move_wheel_files
      isolated=self.isolated,
    File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/wheel.py", line 137, in move_wheel_files
      name, user=user, home=home, root=root, isolated=isolated
    File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/locations.py", line 236, in distutils_scheme
      i.finalize_options()
    File "build/bdist.macosx-10.9-x86_64/egg/setuptools/command/install.py", line 38, in finalize_options
      orig.install.finalize_options(self)
    File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 264, in finalize_options
      "must supply either home or prefix/exec-prefix -- not both"
  DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both
```

I use anaconda with company-mode successfully on my computer at my office running Centos 6.5 (company requirement) and on Ubuntu machines at home, so I am pretty confident in my ability to set up the dependencies on Linux, but this is the only time I have tried to run it on OS X.   Any suggestions?  Thanks.

**Comment by proofit404** [comment]
Hello. You need to install `anaconda_mode` python package into `~/.emacs.d/anaconda-mode/0.1.1/` directory. It must be done automatically but `-t` option doesn't work in python installed with homebrew. Correct your distutils config by removing `prefix` option from it.

Planned to fix it someday as part of #113
