### ISSUE TITLE
Error ServiceException

### ISSUE THREAD

**Issue by nlamirault** [proofit404/anaconda-mode#131]
When i open a Python file, i've got this error : 

```elisp
Debugger entered--Lisp error: (wrong-type-argument stringp ((code . -32700) (message . "Parse error")))
  format-message(((code . -32700) (message . "Parse error")))
  apply(format-message ((code . -32700) (message . "Parse error")))
  error(((code . -32700) (message . "Parse error")))
  #[257 "p\306\307\310\311\312!\313\"\314$\216\304\315 \232\2031r\316\304!q\210\303p\232?\206-\302`\232?\206-\305\317 \232?)\2038\320\321\300\"\202\201b\210\322\3231I\324 0\202a\210\325 \326r\327\330!q\210c\210eb\210p)!\266\331\332!\333\331\"\203r\331\333\331\"A!\202~r\303q\210\301\333\334\"A!))\262)\207" ["eldoc" anaconda-mode-eldoc-callback 760 #<buffer capacity.py> #<window 3 on capacity.py> 1 make-byte-code 0 "\301\300!\207" vconcat vector [kill-buffer] 2 selected-window window-buffer buffer-chars-modified-tick message "Skip anaconda-mode %s response" list (json-readtable-error) json-read buffer-string pop-to-buffer get-buffer-create "*anaconda-response*" error "Can't read anaconda-mode server response" assoc result url-http-end-of-headers json-array-type] 8 "\n\n(fn STATUS)"]((:error (error http 400)))
  apply(#[257 "p\306\307\310\311\312!\313\"\314$\216\304\315 \232\2031r\316\304!q\210\303p\232?\206-\302`\232?\206-\305\317 \232?)\2038\320\321\300\"\202\201b\210\322\3231I\324 0\202a\210\325 \326r\327\330!q\210c\210eb\210p)!\266\331\332!\333\331\"\203r\331\333\331\"A!\202~r\303q\210\301\333\334\"A!))\262)\207" ["eldoc" anaconda-mode-eldoc-callback 760 #<buffer capacity.py> #<window 3 on capacity.py> 1 make-byte-code 0 "\301\300!\207" vconcat vector [kill-buffer] 2 selected-window window-buffer buffer-chars-modified-tick message "Skip anaconda-mode %s response" list (json-readtable-error) json-read buffer-string pop-to-buffer get-buffer-create "*anaconda-response*" error "Can't read anaconda-mode server response" assoc result url-http-end-of-headers json-array-type] 8 "\n\n(fn STATUS)"] (:error (error http 400)))
  url-http-activate-callback()
  url-http-content-length-after-change-function(115 199 84)
  url-http-wait-for-headers-change-function(1 204 203)
  url-http-generic-filter(#<process 127.0.0.1> "HTTP/1.1 400 Bad Request
\nServer: BaseHTTP/0.3 Python/2.7.9
\nDate: Fri, 16 Oct 2015 08:30:14 GMT
\nContent-Length: 83
\n
\n{\"jsonrpc\": \"2.0\", \"id\": null, \"error\": {\"message\": \"Parse error\", \"code\": -32700}}")
```

and in *anaconda-mode* buffer : 
 
```python
You are using pip version 7.0.3, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.[0m
Collecting anaconda-mode==0.1.1
Collecting jedi>=0.9.0 (from anaconda-mode==0.1.1)
  Using cached jedi-0.9.0-py2.py3-none-any.whl
Collecting service-factory>=0.1.2 (from anaconda-mode==0.1.1)
Collecting six (from service-factory>=0.1.2->anaconda-mode==0.1.1)
Installing collected packages: jedi, six, service-factory, anaconda-mode
Successfully installed anaconda-mode jedi service-factory six-1.9.0
anaconda_mode port 9000
127.0.0.1 - - [16/Oct/2015 10:30:14] ================================================================================
Traceback (most recent call last):
  File "/home/vagrant/.emacs.d/anaconda-mode/0.1.1/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/vagrant/.emacs.d/anaconda-mode/0.1.1/service_factory/service.py", line 46, in __call__
    args = self.load_args(arg)
  File "/home/vagrant/.emacs.d/anaconda-mode/0.1.1/service_factory/service.py", line 64, in load_args
    parse_error()
  File "/home/vagrant/.emacs.d/anaconda-mode/0.1.1/service_factory/errors.py", line 31, in parse_error
    raise ServiceException(400, dumps(response))
ServiceException: (400, '{"jsonrpc": "2.0", "id": null, "error": {"message": "Parse error", "code": -32700}}')
```

**Comment by proofit404** [comment]
What is your Emacs version?

**Comment by nlamirault** [comment]
```bash
$ emacs --version
GNU Emacs 25.0.50.2
```

**Comment by proofit404** [comment]
I guess json encoder maybe broken in the Emacs master.

**Comment by proofit404** [comment]
Solved in the `tramp` branch.
