### ISSUE TITLE
Hangs when using Lambda in Map

### ISSUE THREAD

**Issue by mitchellgordon95** [proofit404/anaconda-mode#135]
When I start typing the code:

map(lambda x,y: x)

Anaconda hangs when I get to "x"

I'm on spacemacs.

127.0.0.1 - - [29/Oct/2015 15:15:08] ================================================================================
Traceback (most recent call last):
  File "c:\Users\Megaflux\AppData\Roaming\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\providers\basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "c:\Users\Megaflux\AppData\Roaming\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 49, in __call__
    result = self.apply(method, args)
  File "c:\Users\Megaflux\AppData\Roaming\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 104, in apply
    server_error(args['id'], error)
  File "c:\Users\Megaflux\AppData\Roaming\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\errors.py", line 92, in server_error
    six.raise_from(ServiceException(500, dumps(response)), error)
  File "c:\Users\Megaflux\AppData\Roaming\.emacs.d\.cache\anaconda-mode\0.1.1\six.py", line 718, in raise_from
    raise value
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "KeyError(u\'map\',)"}}')
127.0.0.1 - - [29/Oct/2015 15:15:10] ================================================================================
Traceback (most recent call last):
  File "c:\Users\Megaflux\AppData\Roaming\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\providers\basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "c:\Users\Megaflux\AppData\Roaming\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 49, in __call__
    result = self.apply(method, args)
  File "c:\Users\Megaflux\AppData\Roaming\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 104, in apply
    server_error(args['id'], error)
  File "c:\Users\Megaflux\AppDat... (not sure why this is cut off)

**Comment by proofit404** [comment]
This problem belongs to the `jedi` library. I reported few similar issue into jedi bugtracker. Hope someday I will have some time to research it more deeply.
