### ISSUE TITLE
An error about anaconda-mode in spacemacs

### ISSUE THREAD

**Issue by woonchao** [proofit404/anaconda-mode#153]
Hi, I got a trouble when using anaconda-mode in spacemacs.

The error messages in `*anaconda-mode*` are as follows:
```
Traceback (most recent call last):
  File "/usr/bin/ipython", line 4, in <module>
    from IPython import start_ipython
  File "/usr/lib/python2.7/dist-packages/IPython/__init__.py", line 45, in <module>
    from .config.loader import Config
  File "/usr/lib/python2.7/dist-packages/IPython/config/__init__.py", line 16, in <module>
    from .application import *
  File "/usr/lib/python2.7/dist-packages/IPython/config/application.py", line 32, in <module>
    from IPython.config.configurable import SingletonConfigurable
  File "/usr/lib/python2.7/dist-packages/IPython/config/configurable.py", line 32, in <module>
    from .loader import Config, LazyConfigValue
  File "/usr/lib/python2.7/dist-packages/IPython/config/loader.py", line 34, in <module>
    from IPython.utils.path import filefind, get_ipython_dir
  File "/usr/lib/python2.7/dist-packages/IPython/utils/path.py", line 22, in <module>
    import tempfile
  File "/usr/lib/python2.7/tempfile.py", line 35, in <module>
    from random import Random as _Random
ImportError: cannot import name Random
```

The error log in `*messages*` is
```
error in process sentinel: anaconda-mode-install-sentinel: Can't install `anaconda-mode' server
error in process sentinel: Can't install `anaconda-mode' server
```

Does some people know how to solve this problem?

**Comment by proofit404** [comment]
Try to run following command in your shell
```bash
find / -name random.py 2>/dev/null
```

**Comment by woonchao** [comment]
Well, after I do what @proofit404  and re-install spacemacs it works.  It seems a broken package caused by my poor proxy. :) thx

**Comment by proofit404** [comment]
Glad you solve it.
