### ISSUE TITLE
ananconda failed with rpc error

### ISSUE THREAD

**Issue by dzhwinter** [proofit404/anaconda-mode#155]
when typed a lambda expression, then it failed and then go to the mess after that.

```
reduce((lambda x,y: x+y), blablabla)

anaconda_mode port 9000
127.0.0.1 - - [13/Jan/2016 14:51:13] 
================================================================================
Traceback (most recent call last):
  File "/data01/home/dongzhihong/.emacs.d/.cache/anaconda-mode/0.1.1/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/data01/home/dongzhihong/.emacs.d/.cache/anaconda-mode/0.1.1/service_factory/service.py", line 49, in __call__
    result = self.apply(method, args)
  File "/data01/home/dongzhihong/.emacs.d/.cache/anaconda-mode/0.1.1/service_factory/service.py", line 104, in apply
    server_error(args['id'], error)
  File "/data01/home/dongzhihong/.emacs.d/.cache/anaconda-mode/0.1.1/service_factory/errors.py", line 92, in server_error
    six.raise_from(ServiceException(500, dumps(response)), error)
  File "/data01/home/dongzhihong/.emacs.d/.cache/anaconda-mode/0.1.1/six.py", line 718, in raise_from
    raise value
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "KeyError(u\'sumxy\',)"}}')
```

```
system info 
emacs 24.4.1
Linux n6-131-076 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux
anaconda-mode 1.1.0
```

**Comment by proofit404** [comment]
This is a bug of the `jedi` library. It will be fixed after new `jedi` release.
