### ISSUE TITLE
Server Error: IOError(20, 'not a directory')

### ISSUE THREAD

**Issue by vitiral** [proofit404/anaconda-mode#193]
anaconda mode is hitting an error that keeps popping up. I am running a base install of spacemacs with python-mode enabled.

I opened a ticket there which I will be closing in favor of this ticket:
syl20bnr/spacemacs#6775

**Comment by mrbschroeder** [comment]
I've got the same error — here's the traceback from the `*anaconda-mode*` buffer:

```
anaconda_mode port 54566
127.0.0.1 - - [29/Sep/2016 16:34:53] 
================================================================================
Traceback (most recent call last):
  File "/Users/matthew/.emacs.d/.cache/anaconda-mode/0.1.5/service_factory-0.1.4-py2.7.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/Users/matthew/.emacs.d/.cache/anaconda-mode/0.1.5/service_factory-0.1.4-py2.7.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/Users/matthew/.emacs.d/.cache/anaconda-mode/0.1.5/service_factory-0.1.4-py2.7.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/Users/matthew/.emacs.d/.cache/anaconda-mode/0.1.5/service_factory-0.1.4-py2.7.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "IOError(20, \'Not a directory\')"}}')
```

**Comment by wallrj** [comment]
It could be because the anaconda package has been installed as an egg file (a zip file)

```
[~]$ file /home/richard/.emacs.d/.cache/anaconda-mode/0.1.5/anaconda_mode-0.1.5-py2.7.egg 
/home/richard/.emacs.d/.cache/anaconda-mode/0.1.5/anaconda_mode-0.1.5-py2.7.egg: Zip archive data, at least v2.0 to extract
```

If I unzip the eggs into directories with the same names, the error goes away.

**Comment by proofit404** [comment]
Yet another packaging issue. Great...

Does any one knows why easy_install install packages as zip files? It unpack jedi library on the other side?

**Comment by mrbschroeder** [comment]
@wallrj thank you — that helped a ton. I added a `.pydistutils.cfg` at the root of my home with the following content:

```
[easy_install]
zip_ok = 0
```

and things are working again.

**Comment by vitiral** [comment]
@mrbschroeder 's solution worked for me too!

**Comment by proofit404** [comment]
I roll out new anaconda-mode release.  I mark all python packages zip unsafe, so easy_install will unpack them into directories without any configuration required on your machine. This fix will be available after melpa next build.

**Comment by brettlangdon** [comment]
Hello, I am having this issue and the original solution does not work for me.

I am on `anaconda-mode` `0.1.6`, and all of the eggs here `~/.emacs.d/.cache/anaconda-mode/0.1.6/` are directories not zips, but I am still getting the same issue.

```
anaconda_mode port 54516
127.0.0.1 - - [21/Nov/2016 14:07:27] ================================================================================
Traceback (most recent call last):
  File "/Users/brettlangdon/dotfiles/emacs.d/.cache/anaconda-mode/0.1.6/service_factory-0.1.5-py2.7.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/Users/brettlangdon/dotfiles/emacs.d/.cache/anaconda-mode/0.1.6/service_factory-0.1.5-py2.7.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/Users/brettlangdon/dotfiles/emacs.d/.cache/anaconda-mode/0.1.6/service_factory-0.1.5-py2.7.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/Users/brettlangdon/dotfiles/emacs.d/.cache/anaconda-mode/0.1.6/service_factory-0.1.5-py2.7.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "IOError(20, \'Not a directory\')"}}')
```

```
$ emacs --version
GNU Emacs 25.1.1
```

And I am running spacemacs `0.200.5@25.1.1 (spacemacs)`

Any guidance would be greatly appreciated.

**Comment by proofit404** [comment]
@brettlangdon Literally I have no idea what's going on.

**Comment by brettlangdon** [comment]
@proofit404 is there any additional debugging I can do from my end?

I do have the `anaconda_mode` process running it seems:

```
$ ps aux |grep anaconda_mode
brettlangdon     53579   0.0  0.2  2488820  27236 s001  Ss+   2:11PM   0:00.36 /usr/bin/python /usr/local/bin/ipython -c \012import sys, site\012site.addsitedir('.')\012import anaconda_mode\012anaconda_mode.main(sys.argv[1:])\012
```

**Comment by brettlangdon** [comment]
Here we go... making some progress:

```
anaconda_mode port 54960
Traceback (most recent call last):
  File "/Users/brettlangdon/dotfiles/emacs.d/.cache/anaconda-mode/0.1.6/service_factory-0.1.5-py2.7.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "/Users/brettlangdon/dotfiles/emacs.d/.cache/anaconda-mode/0.1.6/anaconda_mode-0.1.6-py2.7.egg/anaconda_mode.py", line 27, in wrapper
    return f(Script(source, line, column, path))
  File "/Users/brettlangdon/dotfiles/emacs.d/.cache/anaconda-mode/0.1.6/jedi-0.9.0-py2.7.egg/jedi/api/__init__.py", line 107, in __init__
    self._grammar = load_grammar('grammar%s.%s' % sys.version_info[:2])
  File "/Users/brettlangdon/dotfiles/emacs.d/.cache/anaconda-mode/0.1.6/jedi-0.9.0-py2.7.egg/jedi/parser/__init__.py", line 51, in load_grammar
    return _loaded_grammars.setdefault(path, generate_grammar(path))
  File "/Users/brettlangdon/dotfiles/emacs.d/.cache/anaconda-mode/0.1.6/jedi-0.9.0-py2.7.egg/jedi/parser/pgen2/pgen.py", line 393, in generate_grammar
    p = ParserGenerator(filename)
  File "/Users/brettlangdon/dotfiles/emacs.d/.cache/anaconda-mode/0.1.6/jedi-0.9.0-py2.7.egg/jedi/parser/pgen2/pgen.py", line 18, in __init__
    stream = open(filename)
IOError: [Errno 20] Not a directory: '/Users/brettlangdon/dotfiles/emacs.d/.cache/anaconda-mode/0.1.6/jedi-0.9.0-py2.7.egg/jedi/parser/grammar2.7.txt'
```

**Comment by proofit404** [comment]
Try to do following in your shell:
```shell
cd ~/.emacs.d/anaconda-mode/0.1.6
rm easy-install.pth
mv anaconda_mode-0.1.6-py3.4.egg/anaconda_mode.py .
mv jedi-0.9.0-py3.4.egg/jedi .
mv service_factory-0.1.5-py3.4.egg/service_factory .
rm -rf *.egg
```
Then add following lines to your config:
```lisp
(setq naconda-mode-server-command "
import sys
import anaconda_mode
anaconda_mode.main(sys.argv[1:])
")
```
Then restart your emacs and see if this works.

**Comment by proofit404** [comment]
Hm. I have `grammar2.7.txt` file in my installation.

**Comment by brettlangdon** [comment]
yeah... it seems as thought `jedi` was still a zip and not a directory... sorry about that.

**Comment by proofit404** [comment]
I've added always unzip option to the server installation command. Lets see if next melpa build will fix this problem for you.

**Comment by brettlangdon** [comment]
awesome, thanks @proofit404

**Comment by nascarsayan** [comment]
I am having the same problem as @brettlangdon 
```
anaconda_mode port 45955
127.0.0.1 - - [20/Jun/2017 22:13:10] ================================================================================
Traceback (most recent call last):
  File "/home/nascarsayan/.emacs.d/.cache/anaconda-mode/0.1.8/service_factory-0.1.5-py2.7.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/nascarsayan/.emacs.d/.cache/anaconda-mode/0.1.8/service_factory-0.1.5-py2.7.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/nascarsayan/.emacs.d/.cache/anaconda-mode/0.1.8/service_factory-0.1.5-py2.7.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/nascarsayan/.emacs.d/.cache/anaconda-mode/0.1.8/service_factory-0.1.5-py2.7.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "ValueError(\'need more than 0 values to unpack\',)"}}')
127.0.0.1 - - [20/Jun/2017 22:20:25] ================================================================================
```

How to solve this?

**Comment by nascarsayan** [comment]
#234 contains details when this error occurs; in my case, while writing methods and variables from * imports, and a "." after a module name cause problems

**Comment by proofit404** [comment]
Code related to this issue was changed a lot in recent days. If anyone affected by this issue, please, submit the new one.
