### ISSUE TITLE
anaconda-mode:importError: No module named BaseHTTPServer

### ISSUE THREAD

**Issue by hyloong** [proofit404/anaconda-mode#194]
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "build/bdist.macosx-10.11-intel/egg/anaconda_mode.py", line 18, in <module>
  File "build/bdist.macosx-10.11-intel/egg/service_factory/__init__.py", line 14, in <module>
  File "build/bdist.macosx-10.11-intel/egg/service_factory/factory.py", line 14, in <module>
  File "build/bdist.macosx-10.11-intel/egg/service_factory/providers/basehttp.py", line 18, in <module>
ImportError: No module named BaseHTTPServer

I installed company-anaconda,  when i m-x anaconda-mode return , message show "Anaconda mode enabled in current buffer", but when i input same code, the anaconda-mode buffer one error happend, import BaseHTTPServer.py errer. Can not start ‘anaconda-mode’ server. 
In shell, i command "python" that into python shell, command "import BaseHTTPServer", it can find.

So how can i fit this error? Thanks

**Comment by proofit404** [comment]
Does solution described in #188 issue helps you?

**Comment by proofit404** [comment]
Solved in the 0.1.3
