### ISSUE TITLE
[bug] dot complete meet a bug

### ISSUE THREAD

**Issue by dzhwinter** [proofit404/anaconda-mode#199]
when type dot complete, It give me the exception
```
127.0.0.1 - - [07/Sep/2016 23:55:26] ================================================================================
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/usr/local/lib/python2.7/site-packages/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/usr/local/lib/python2.7/site-packages/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/usr/local/lib/python2.7/site-packages/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "UnboundLocalError(\\"local variable \'module_path\' referenced\
 before assignment\\",)"}}')
```

system info
```
#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 4f3361c)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion :variables auto-completion-enable-help-tooltip t
                 (org :variables org-enable-github-support t)
                 (python :variables python-enable-yapf-format-on-save t)
                 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
                 (go :variables go-use-gometalinter t gofmt-command "goimports" go-tab-width 2))
```

```

**Comment by proofit404** [comment]
I need python buffer content and exact point position. Does this error persist on any dot complete or it happens periodic?

**Comment by dzhwinter** [comment]
it failed every time when i typed dot. Other packages complete well.
Tensorflow is a big package , and only this module will meet the bug.

The file I edited 
```
import tensorflow as tf
tf.  "here"
tf.ops. "here"
``` 

```
127.0.0.1 - - [08/Sep/2016 12:50:17] ================================================================================
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/usr/local/lib/python2.7/site-packages/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/usr/local/lib/python2.7/site-packages/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/usr/local/lib/python2.7/site-packages/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "UnboundLocalError(\\"local variable \'module_path\' referenced\
 before assignment\\",)"}}')
```

And sure this package *can* be completed, I mean that its not this package's bug.
for example, I import it into ipython
![image](https://cloud.githubusercontent.com/assets/6687176/18337480/a35360a0-75c3-11e6-8255-45ffcfcb1691.png)

**Comment by proofit404** [comment]
I think this is a `jedi` library bug, please report it to their bugtracker.
