### ISSUE TITLE
ServiceException on completion

### ISSUE THREAD

**Issue by k1-hedayati** [proofit404/anaconda-mode#231]
I get this error when I'm typing python code
```
127.0.0.1 - - [05/Mar/2017 11:14:35] ================================================================================
Traceback (most recent call last):
  File "/home/k1/.emacs.d/anaconda-mode/0.1.6/service_factory-0.1.5-py2.7.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "/home/k1/.emacs.d/anaconda-mode/0.1.6/anaconda_mode-0.1.6-py2.7.egg/anaconda_mode.py", line 27, in wrapper
    return f(Script(source, line, column, path))
  File "/home/k1/.emacs.d/anaconda-mode/0.1.6/anaconda_mode-0.1.6-py2.7.egg/anaconda_mode.py", line 51, in wrapper
    for definition in f(script)]
  File "/home/k1/.emacs.d/anaconda-mode/0.1.6/anaconda_mode-0.1.6-py2.7.egg/anaconda_mode.py", line 51, in <listcomp>
    for definition in f(script)]
  File "/home/k1/.emacs.d/anaconda-mode/0.1.6/jedi-0.10.0-py2.7.egg/jedi/api/classes.py", line 301, in full_name
    path = list(self._path())
  File "/home/k1/.emacs.d/anaconda-mode/0.1.6/jedi-0.10.0-py2.7.egg/jedi/api/classes.py", line 180, in _path
    return reversed(list(to_reverse()))
  File "/home/k1/.emacs.d/anaconda-mode/0.1.6/jedi-0.10.0-py2.7.egg/jedi/api/classes.py", line 161, in to_reverse
    module_context, = name.infer()
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/k1/.emacs.d/anaconda-mode/0.1.6/service_factory-0.1.5-py2.7.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/k1/.emacs.d/anaconda-mode/0.1.6/service_factory-0.1.5-py2.7.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/k1/.emacs.d/anaconda-mode/0.1.6/service_factory-0.1.5-py2.7.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/k1/.emacs.d/anaconda-mode/0.1.6/service_factory-0.1.5-py2.7.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"id": 1, "jsonrpc": "2.0", "error": {"data": "ValueError(\'not enough values to unpack (expected 1, got 0)\',)", "message": "Server error", "code": -32000}}')
```

**Comment by proofit404** [comment]
Try to use `jedi` from master. You can find instructions in the nearest issue about failed installation.
