### ISSUE TITLE
An error with jedi to start the server

### ISSUE THREAD

**Issue by VonFry** [proofit404/anaconda-mode#232]
System: macOS
Python version: 3.6
Jedi Version: 0.10.0

The log in `*anaconda mode*`:
```
anaconda_mode port 49787
127.0.0.1 - - [06/Mar/2017 15:08:21] ================================================================================
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "/usr/local/lib/python3.6/site-packages/anaconda_mode.py", line 27, in wrapper
    return f(Script(source, line, column, path))
  File "/usr/local/lib/python3.6/site-packages/anaconda_mode.py", line 49, in wrapper
    for definition in f(script)]
  File "/usr/local/lib/python3.6/site-packages/anaconda_mode.py", line 49, in <listcomp>
    for definition in f(script)]
  File "/usr/local/lib/python3.6/site-packages/jedi/api/classes.py", line 301, in full_name
    path = list(self._path())
  File "/usr/local/lib/python3.6/site-packages/jedi/api/classes.py", line 180, in _path
    return reversed(list(to_reverse()))
  File "/usr/local/lib/python3.6/site-packages/jedi/api/classes.py", line 161, in to_reverse
    module_context, = name.infer()
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/usr/local/lib/python3.6/site-packages/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/usr/local/lib/python3.6/site-packages/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/usr/local/lib/python3.6/site-packages/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "ValueError(\'not enough values to unpack (expected 1, got 0)\',)"}}')

```

**Comment by proofit404** [comment]
Hi,

Thank you for report. This is known issue in jedi library. I guess we should wait for next jedi release. Otherwise you can try to use jedi from master. You can find installation instructions in the issue below.

https://github.com/proofit404/anaconda-mode/issues/225#issuecomment-280009142
