### ISSUE TITLE
Cannot get code completion for libraries only installed in a virtual environment

### ISSUE THREAD

**Issue by zrwang** [proofit404/anaconda-mode#234]
I am a Spacemacs User. I enabled auto-completion and python layer, and activated the virtual environment within emacs. For the following testing code in a buffer,

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import numpy as np
import cv2
import os
import sys

if __name__ == '__main__':
   sys.
   os.
   cv2.
   np.
```

I can get a popup window for `sys` after I input a dot. However I cannot get popup windows for `os`, `cv2`, and `np`. 

I installed `numpy` within the virtual environment via pip, and complied `opencv` library and sym-linked the `cv2.so` to the virtual environment.

Another interesting phenomenon is that I can get popup windows for `cv2`, `np` and `sys` (`os` still does not work) in Python Console Buffer.

Here is the output from my anaconda-mode buffer:

```
anaconda_mode port 44376
127.0.0.1 - - [11/Mar/2017 01:13:36] ================================================================================
Traceback (most recent call last):
  File "/home/zrwang/.virtualenvs/cv/lib/python2.7/site-packages/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/zrwang/.virtualenvs/cv/lib/python2.7/site-packages/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/zrwang/.virtualenvs/cv/lib/python2.7/site-packages/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/zrwang/.virtualenvs/cv/lib/python2.7/site-packages/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "ValueError(\'need more than 0 values to unpack\',)"}}')

Process anaconda-mode killed
anaconda_mode port 45122
127.0.0.1 - - [11/Mar/2017 01:16:04] ================================================================================
Traceback (most recent call last):
  File "/home/zrwang/.virtualenvs/cv/lib/python2.7/site-packages/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/zrwang/.virtualenvs/cv/lib/python2.7/site-packages/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/zrwang/.virtualenvs/cv/lib/python2.7/site-packages/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/zrwang/.virtualenvs/cv/lib/python2.7/site-packages/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "ValueError(\'need more than 0 values to unpack\',)"}}')
```

Thanks!

**Comment by proofit404** [comment]
Hi, 

Try to use jedi from master. You can find installation instructions in the nearest issue about python package installation.

**Comment by zrwang** [comment]
Thanks for your prompt reply.

I tried jedi from master by reinstalled the jedi in my virtual environment using the following command

```
pip install -e git://github.com/davidhalter/jedi.git#egg=jedi
```

However, it didn't solve my issue. I still cannot get those completions.

**Comment by proofit404** [comment]
Anaconda mode use its own jedi installation. I'm not sure if your installation will take precedence.

**Comment by zrwang** [comment]
Got you. So you ask me to try the jedi from master by replacing the anaconda mode built-in jedi installation. Could you give me more specific information about where can I find the installation instructions? For example, a link. Thanks a lot.

**Comment by zrwang** [comment]
It seems I found it. Is that something like this?

```
M-: (dired (anaconda-mode-server-directory)) RET
M-! rm -rf jedi* RET
M-! pip install "jedi<0.9" -t . RET
```

I tried this also. No luck...

**Comment by proofit404** [comment]
https://github.com/proofit404/anaconda-mode/issues/225#issuecomment-280009142

You need to do same steps except checkout git tag.

**Comment by zrwang** [comment]
Thank you for your help. Actually I have tried that also. Now the symptom is that dot completion works well for all the global libraries (`sys`, `os`, etc.) For the libraries installed in the virtual environment (like `numpy`, `opencv 3.0 (cv2)`), it does not work after I input the dot but works after I input another letter after the dot. For example: (`|` represents the cursor)

```
cv2.| #not working
cv2.i| #working
```

So, I am wondering it's not working properly because the libraries (cv2) has too many attributes and methods?

**Comment by nelson-liu** [comment]
I'm seeing the same symptoms as @zrwang . Perhaps we should reopen this issue?

**Comment by proofit404** [comment]
Did you activate your virtual environment inside Emacs?

**Comment by nelson-liu** [comment]
yup, using `pyvenv`. The completion works perfectly as long as the point is not directly after a `.` it seems. (just like what @zrwang ) is seeing,  which seems a bit odd.
I'm running jedi on the latest master. The contents of the `*anaconda-mode*` buffer when i try to do completion right after a `.` is:
```
127.0.0.1 - - [06/May/2017 19:40:36] ================================================================================
Traceback (most recent call last):
  File "/Users/nfliu/dotfiles/emacs.d/.cache/anaconda-mode/0.1.8/service_factory-0.1.5-py3.6.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "/Users/nfliu/dotfiles/emacs.d/.cache/anaconda-mode/0.1.8/anaconda_mode-0.1.8-py3.6.egg/anaconda_mode.py", line 27, in wrapper
    return f(Script(source, line, column, path))
  File "/Users/nfliu/dotfiles/emacs.d/.cache/anaconda-mode/0.1.8/anaconda_mode-0.1.8-py3.6.egg/anaconda_mode.py", line 49, in wrapper
    for definition in f(script)]
  File "/Users/nfliu/dotfiles/emacs.d/.cache/anaconda-mode/0.1.8/anaconda_mode-0.1.8-py3.6.egg/anaconda_mode.py", line 49, in <listcomp>
    for definition in f(script)]
  File "/Users/nfliu/dotfiles/emacs.d/.cache/anaconda-mode/0.1.8/jedi-0.10.3-py3.6.egg/jedi/api/classes.py", line 299, in full_name
    path = list(self._path())
  File "/Users/nfliu/dotfiles/emacs.d/.cache/anaconda-mode/0.1.8/jedi-0.10.3-py3.6.egg/jedi/api/classes.py", line 181, in _path
    return reversed(list(to_reverse()))
  File "/Users/nfliu/dotfiles/emacs.d/.cache/anaconda-mode/0.1.8/jedi-0.10.3-py3.6.egg/jedi/api/classes.py", line 162, in to_reverse
    module_context, = name.infer()
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nfliu/dotfiles/emacs.d/.cache/anaconda-mode/0.1.8/service_factory-0.1.5-py3.6.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/Users/nfliu/dotfiles/emacs.d/.cache/anaconda-mode/0.1.8/service_factory-0.1.5-py3.6.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/Users/nfliu/dotfiles/emacs.d/.cache/anaconda-mode/0.1.8/service_factory-0.1.5-py3.6.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/Users/nfliu/dotfiles/emacs.d/.cache/anaconda-mode/0.1.8/service_factory-0.1.5-py3.6.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"error": {"message": "Server error", "code": -32000, "data": "ValueError(\'not enough values to unpack (expected 1, got 0)\',)"}, "jsonrpc": "2.0", "id": 1}')
```

**Comment by proofit404** [comment]
This error happens in the jedi library. I can't fix it in the anaconda-mode.

**Comment by nelson-liu** [comment]
got it, thanks for the info! anaconda-mode is literally a godsend for python development in emacs, so thanks for maintaining it as well.
