### ISSUE TITLE
ValueError when trying to find assignments

### ISSUE THREAD

**Issue by sivakov512** [proofit404/anaconda-mode#241]
Hello!

I get ServiceExceptions with ValueError when I call `anaconda-mode-find-assignments`
```
127.0.0.1 - - [07/Apr/2017 12:44:55] ================================================================================
Traceback (most recent call last):
  File "/home/cryptomaniac/.emacs.d/anaconda-mode/0.1.8/service_factory-0.1.5-py2.7.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/cryptomaniac/.emacs.d/anaconda-mode/0.1.8/service_factory-0.1.5-py2.7.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/cryptomaniac/.emacs.d/anaconda-mode/0.1.8/service_factory-0.1.5-py2.7.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/cryptomaniac/.emacs.d/anaconda-mode/0.1.8/service_factory-0.1.5-py2.7.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "ValueError(\'need more than 0 values to unpack\',)"}}')
```

When I call `anaconda-mode-find-definitions` I get message "No definitions found".

All this works correctly with jedi==0.8, but not with latest Jedi versions.
I would be glad to use jedi==0.8, because it has no problems, but it does not show argument names in eldoc.

**Comment by jrab89** [comment]
I'm having a similar problem when I try to get completions for the `mock` module:

```
127.0.0.1 - - [03/May/2017 09:15:56] ================================================================================
Traceback (most recent call last):
  File "/Users/jrabovsky/git_repos/emacs_v3/anaconda-mode/0.1.8/service_factory-0.1.5-py2.7.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/Users/jrabovsky/git_repos/emacs_v3/anaconda-mode/0.1.8/service_factory-0.1.5-py2.7.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/Users/jrabovsky/git_repos/emacs_v3/anaconda-mode/0.1.8/service_factory-0.1.5-py2.7.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/Users/jrabovsky/git_repos/emacs_v3/anaconda-mode/0.1.8/service_factory-0.1.5-py2.7.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "ValueError(\'need more than 0 values to unpack\',)"}}')
```
Python 2.7.13
jedi 0.10.2
mock 2.0.0

**Comment by nascarsayan** [comment]
I am having the same problem too
`anaconda_mode port 35182
127.0.0.1 - - [20/Jun/2017 21:48:45] ================================================================================
Traceback (most recent call last):
  File "/home/nascarsayan/.emacs.d/.cache/anaconda-mode/0.1.8/service_factory-0.1.5-py2.7.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/nascarsayan/.emacs.d/.cache/anaconda-mode/0.1.8/service_factory-0.1.5-py2.7.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/nascarsayan/.emacs.d/.cache/anaconda-mode/0.1.8/service_factory-0.1.5-py2.7.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/nascarsayan/.emacs.d/.cache/anaconda-mode/0.1.8/service_factory-0.1.5-py2.7.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "ValueError(\'need more than 0 values to unpack\',)"}}')`

**Comment by proofit404** [comment]
Fixed in master.
