### ISSUE TITLE
doesn't work with numpy 

### ISSUE THREAD

**Issue by xiadingZ** [proofit404/anaconda-mode#243]
I'm using anaconda-mode in spacemacs, I can get complements on standard library, but when I try to complete statements about numpy, it will throw error:

```
import numpy as np
a = np.array([1])
a.
```

Error message is:
```
anaconda_mode port 46477
127.0.0.1 - - [08/Apr/2017 15:08:17] ================================================================================
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "/usr/lib/python3.6/site-packages/anaconda_mode.py", line 27, in wrapper
    return f(Script(source, line, column, path))
  File "/usr/lib/python3.6/site-packages/anaconda_mode.py", line 49, in wrapper
    for definition in f(script)]
  File "/usr/lib/python3.6/site-packages/anaconda_mode.py", line 49, in <listcomp>
    for definition in f(script)]
  File "/usr/lib/python3.6/site-packages/jedi/api/classes.py", line 301, in full_name
    path = list(self._path())
  File "/usr/lib/python3.6/site-packages/jedi/api/classes.py", line 180, in _path
    return reversed(list(to_reverse()))
  File "/usr/lib/python3.6/site-packages/jedi/api/classes.py", line 161, in to_reverse
    module_context, = name.infer()
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/usr/lib/python3.6/site-packages/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/usr/lib/python3.6/site-packages/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/usr/lib/python3.6/site-packages/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "ValueError(\'not enough values to unpack (expected 1, got 0)\',)"}}')

```
OS: Arch Linux
Python: 3.6
numpy: 1.12.0---mkl
emacs: 26.0.50

**Comment by proofit404** [comment]
Hi.

Have you activate virtualenv in Emacs?

**Comment by xiadingZ** [comment]
No

**Comment by wizmer** [comment]
I don't know what causes the crash but the fact that the completion is not working is a Jedi issue. 
Basically, and from what I have understood, since numpy functions are C functions Jedi has to rely on the numpy docstring to perform the static analysis. And the numpy docstring format is not standard. There is a pending PR to solve this problem here: https://github.com/davidhalter/jedi/pull/868

And the overall issue is discuessed here: https://github.com/davidhalter/jedi/issues/372

**Comment by proofit404** [comment]
So yeh, this issue can't be solved by anaconda-mode.

**Comment by proofit404** [comment]
@xiadingX You can find instructions for virtualenv
integration in the README.
