### ISSUE TITLE
can not complete built-in os package

### ISSUE THREAD

**Issue by ashfinal** [proofit404/anaconda-mode#250]
Other packages works well, but built-in `os` package runs into error.
``` bash
127.0.0.1 - - [24/May/2017 19:08:15] ================================================================================
Traceback (most recent call last):
  File "/Users/ashfinal/.emacs.d/.cache/anaconda-mode/0.1.8/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "/Users/ashfinal/.emacs.d/.cache/anaconda-mode/0.1.8/anaconda_mode.py", line 27, in wrapper
    return f(Script(source, line, column, path))
  File "/Users/ashfinal/.emacs.d/.cache/anaconda-mode/0.1.8/anaconda_mode.py", line 49, in wrapper
    for definition in f(script)]
  File "/Users/ashfinal/.emacs.d/.cache/anaconda-mode/0.1.8/anaconda_mode.py", line 49, in <listcomp>
    for definition in f(script)]
  File "/Users/ashfinal/.emacs.d/.cache/anaconda-mode/0.1.8/jedi/api/classes.py", line 301, in full_name
    path = list(self._path())
  File "/Users/ashfinal/.emacs.d/.cache/anaconda-mode/0.1.8/jedi/api/classes.py", line 180, in _path
    return reversed(list(to_reverse()))
  File "/Users/ashfinal/.emacs.d/.cache/anaconda-mode/0.1.8/jedi/api/classes.py", line 161, in to_reverse
    module_context, = name.infer()
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ashfinal/.emacs.d/.cache/anaconda-mode/0.1.8/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/Users/ashfinal/.emacs.d/.cache/anaconda-mode/0.1.8/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/Users/ashfinal/.emacs.d/.cache/anaconda-mode/0.1.8/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/Users/ashfinal/.emacs.d/.cache/anaconda-mode/0.1.8/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "ValueError(\'not enough values to unpack (expected 1, got 0)\',)"}}')
```
Since the plugin [anaconda](https://github.com/DamnWidget/anaconda/) for Sublime Text works well on my machine, which also use the liberary `jedi`. I would assume anaconda-mode does wrong somewhere.

**Comment by proofit404** [comment]
Which `jedi` version is used in the sublime package? Which version is installed in the `~/.emacs.d/anaconda-mode` directory?

**Comment by ashfinal** [comment]
`jedi` version in sublime package is "0.10.0",  `anaconda-mode` installed "0.10.2".

**Comment by proofit404** [comment]
Thanks, let see what I can do.

**Comment by mackong** [comment]
Same problem here.

```
127.0.0.1 - - [23/Aug/2017 13:35:12] ================================================================================
Traceback (most recent call last):
  File "/home/mackong/.emacs.d/anaconda-mode/0.1.8/service_factory-0.1.5-py3.6.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "/home/mackong/.emacs.d/anaconda-mode/0.1.8/anaconda_mode-0.1.8-py3.6.egg/anaconda_mode.py", line 27, in wrapper
    return f(Script(source, line, column, path))
  File "/home/mackong/.emacs.d/anaconda-mode/0.1.8/anaconda_mode-0.1.8-py3.6.egg/anaconda_mode.py", line 49, in wrapper
    for definition in f(script)]
  File "/home/mackong/.emacs.d/anaconda-mode/0.1.8/anaconda_mode-0.1.8-py3.6.egg/anaconda_mode.py", line 49, in <listcomp>
    for definition in f(script)]
  File "/usr/lib/python3.6/site-packages/jedi/api/classes.py", line 301, in full_name
    path = list(self._path())
  File "/usr/lib/python3.6/site-packages/jedi/api/classes.py", line 180, in _path
    return reversed(list(to_reverse()))
  File "/usr/lib/python3.6/site-packages/jedi/api/classes.py", line 161, in to_reverse
    module_context, = name.infer()
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mackong/.emacs.d/anaconda-mode/0.1.8/service_factory-0.1.5-py3.6.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/mackong/.emacs.d/anaconda-mode/0.1.8/service_factory-0.1.5-py3.6.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/mackong/.emacs.d/anaconda-mode/0.1.8/service_factory-0.1.5-py3.6.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/mackong/.emacs.d/anaconda-mode/0.1.8/service_factory-0.1.5-py3.6.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "ValueError(\'not enough values to unpack (expected 1, got 0)\',)"}}')
```

The code is:
```python
#!/usr/bin/env python3

import os

for x in range(10):
    os.
```

The environment is:
GNU Emacs 25.2.1 (x86_64-redhat-linux-gnu, GTK+ Version 3.22.16) of 2017-07-17
anaconda-mode 0.1.8
jedi 0.10.2

**Comment by et2010** [comment]
This is a known issue of jedi, see the discussion here:

https://github.com/davidhalter/jedi/issues/873

And there is a fix proposed by @shahinism:

https://github.com/davidhalter/jedi/compare/master...shahinism:bug/%2523873?expand=1

The PR is not created yet, but you can patch it manually. And it works:


![default](https://user-images.githubusercontent.com/11584902/30010060-a3f1aab8-915f-11e7-8723-cb9c4a2a4097.png)

**Comment by proofit404** [comment]
Fixed in master.
