### ISSUE TITLE
ImportError: cannot import name 'NotFoundError'

### ISSUE THREAD

**Issue by flhp** [proofit404/anaconda-mode#260]
Hi!
I get the following error when running anaconda-mode with jedi (0.11.0):
```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/usr/lib/python3.6/site-packages/anaconda_mode.py", line 17, in <module>
    from jedi import Script, NotFoundError
ImportError: cannot import name 'NotFoundError'
```

Jedi doesn't seem to have a `NotFoundError` anymore. For me, simply not importing that error in `anaconda_mode.py` does the trick for now:
```
from jedi import Script
from service_factory import service_factory


def script_method(f):
    """Create jedi.Script instance and apply f to it."""

    @wraps(f)
    def wrapper(source, line, column, path):
        try:
            return f(Script(source, line, column, path))
        except:
            return []

    return wrapper
```
Not sure what errors jedi throws now, so just excepting all but that's not really ideal.

Cheers!

**Comment by proofit404** [comment]
Fixed in 0.1.9
