### ISSUE TITLE
FileNotFoundError in anaconda-mode

### ISSUE THREAD

**Issue by zhd173** [proofit404/anaconda-mode#301]
Emacs 27.0.50
macOS 10.13.4
Python 3.6.5

when I try complete some code, *aonaconda-mode* returned this:

``` cmd
127.0.0.1 - - [07/Jun/2018 10:31:46] ================================================================================
Traceback (most recent call last):
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/service_factory-0.1.5-py3.6.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/anaconda_mode-0.1.11-py3.6.egg/anaconda_mode.py", line 33, in wrapper
    return f(Script(source, line, column, path, environment=script_env))
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/anaconda_mode-0.1.11-py3.6.egg/anaconda_mode.py", line 56, in wrapper
    for definition in f(script)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/anaconda_mode-0.1.11-py3.6.egg/anaconda_mode.py", line 67, in complete
    return script.completions()
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/api/__init__.py", line 174, in completions
    completions = completion.completions()
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/api/completion.py", line 97, in completions
    completion_names = self._get_context_completions()
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/api/completion.py", line 198, in _get_context_completions
    completion_names += self._global_completions()
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/api/completion.py", line 223, in _global_completions
    completion_names += filter.values()
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/filters.py", line 200, in values
    return self._convert_names(name for name_list in self._used_names.values()
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/utils.py", line 20, in wrapper
    return list(func(*args, **kwargs))
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/filters.py", line 267, in _convert_names
    for name in names:
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/filters.py", line 201, in <genexpr>
    for name in self._filter(name_list))
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/filters.py", line 226, in _filter
    return list(self._check_flows(names))
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/filters.py", line 243, in _check_flows
    origin_scope=self._origin_scope
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/flow_analysis.py", line 77, in reachability_check
    return _break_check(context, context_scope, first_flow_scope, node)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/flow_analysis.py", line 92, in _break_check
    reachable = _check_if(context, flow_node)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/flow_analysis.py", line 112, in _check_if
    types = context.eval_node(node)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/base_context.py", line 139, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/__init__.py", line 194, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/__init__.py", line 206, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/__init__.py", line 210, in _eval_element_cached
    return eval_node(context, element)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/syntax_tree.py", line 103, in eval_node
    context_set = eval_trailer(context, context_set, trailer)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/syntax_tree.py", line 189, in eval_trailer
    return base_contexts.execute(args)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/common/context.py", line 65, in mapper
    for context in self._set
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/common/context.py", line 34, in from_sets
    sets = list(sets)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/common/context.py", line 65, in <genexpr>
    for context in self._set
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/base_context.py", line 50, in execute
    return stdlib.execute(self.evaluator, self, arguments)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/stdlib.py", line 75, in execute
    return func(evaluator, obj, arguments)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/stdlib.py", line 114, in wrapper
    lst = list(arguments.eval_argument_clinic(clinic_args))
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/arguments.py", line 47, in eval_argument_clinic
    values = NO_CONTEXTS if argument is None else argument.infer()
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/lazy_context.py", line 46, in infer
    return self._context.eval_node(self.data)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/base_context.py", line 139, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/__init__.py", line 194, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/__init__.py", line 206, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/__init__.py", line 210, in _eval_element_cached
    return eval_node(context, element)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/syntax_tree.py", line 72, in eval_node
    return eval_atom(context, element)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/syntax_tree.py", line 208, in eval_atom
    search_global=True
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/_compatibility.py", line 264, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/base_context.py", line 156, in py__getattribute__
    return f.find(filters, attribute_lookup=not search_global)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/finder.py", line 67, in find
    types = self._names_to_types(names, attribute_lookup)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/finder.py", line 178, in _names_to_types
    contexts = ContextSet.from_sets(name.infer() for name in names)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/common/context.py", line 34, in from_sets
    sets = list(sets)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/finder.py", line 178, in <genexpr>
    contexts = ContextSet.from_sets(name.infer() for name in names)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/filters.py", line 142, in infer
    return self.get_param().infer()
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/dynamic.py", line 46, in infer
    return ContextSet.from_sets(p.infer() for p in self._executed_params)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/common/context.py", line 34, in from_sets
    sets = list(sets)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/dynamic.py", line 46, in <genexpr>
    return ContextSet.from_sets(p.infer() for p in self._executed_params)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/param.py", line 34, in infer
    return self._lazy_context.infer()
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/lazy_context.py", line 46, in infer
    return self._context.eval_node(self.data)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/base_context.py", line 139, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/__init__.py", line 194, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/__init__.py", line 206, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/__init__.py", line 210, in _eval_element_cached
    return eval_node(context, element)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/syntax_tree.py", line 72, in eval_node
    return eval_atom(context, element)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/syntax_tree.py", line 208, in eval_atom
    search_global=True
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/_compatibility.py", line 264, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/base_context.py", line 156, in py__getattribute__
    return f.find(filters, attribute_lookup=not search_global)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/finder.py", line 56, in find
    names = self.filter_name(filters)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/finder.py", line 142, in filter_name
    names = filter.get(self._string_name)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/filters.py", line 194, in get
    return self._convert_names(self._filter(names))
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/filters.py", line 226, in _filter
    return list(self._check_flows(names))
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/filters.py", line 243, in _check_flows
    origin_scope=self._origin_scope
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/flow_analysis.py", line 77, in reachability_check
    return _break_check(context, context_scope, first_flow_scope, node)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/flow_analysis.py", line 92, in _break_check
    reachable = _check_if(context, flow_node)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/flow_analysis.py", line 112, in _check_if
    types = context.eval_node(node)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/base_context.py", line 139, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/__init__.py", line 194, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/__init__.py", line 206, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/__init__.py", line 210, in _eval_element_cached
    return eval_node(context, element)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/syntax_tree.py", line 116, in eval_node
    context_set = context.eval_node(element.children[-1])
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/base_context.py", line 139, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/__init__.py", line 194, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/__init__.py", line 206, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/__init__.py", line 210, in _eval_element_cached
    return eval_node(context, element)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/syntax_tree.py", line 72, in eval_node
    return eval_atom(context, element)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/syntax_tree.py", line 208, in eval_atom
    search_global=True
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/_compatibility.py", line 264, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/base_context.py", line 156, in py__getattribute__
    return f.find(filters, attribute_lookup=not search_global)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/finder.py", line 67, in find
    types = self._names_to_types(names, attribute_lookup)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/finder.py", line 178, in _names_to_types
    contexts = ContextSet.from_sets(name.infer() for name in names)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/common/context.py", line 34, in from_sets
    sets = list(sets)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/finder.py", line 178, in <genexpr>
    contexts = ContextSet.from_sets(name.infer() for name in names)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/filters.py", line 142, in infer
    return self.get_param().infer()
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/filters.py", line 145, in get_param
    params = self.parent_context.get_params()
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/context/function.py", line 244, in get_params
    return self.var_args.get_params(self)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/arguments.py", line 82, in get_params
    execution_context.tree_node
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/dynamic.py", line 90, in search_params
    string_name=string_name,
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/utils.py", line 20, in wrapper
    return list(func(*args, **kwargs))
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/dynamic.py", line 124, in _search_function_executions
    evaluator, [module_context], string_name):
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/imports.py", line 569, in get_modules_containing_name
    m = check_fs(p)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/jedi-0.12.0-py3.6.egg/jedi/evaluate/imports.py", line 536, in check_fs
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/zhd/Botpy/Yobee-Agent-Dealer/blaster/tasks/.#reports.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/service_factory-0.1.5-py3.6.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/service_factory-0.1.5-py3.6.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/service_factory-0.1.5-py3.6.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/Users/zhd/.emacs.d/.cache/anaconda-mode/0.1.11/service_factory-0.1.5-py3.6.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "FileNotFoundError(2, \'No such file or directory\')"}}')

```

**Comment by zhd173** [comment]
where my spacemacs dotfile is [here](https://github.com/zhd173/.spacemacs.d/blob/master/init.el).

**Comment by proofit404** [comment]
Hi.

Spacemacs is too big for me to debug. Please provide easier config which can be used as an argument to `emacs -Q`.

Also, I need problematic code base and detailed instructions to set up its environment.

**Comment by zhd173** [comment]
Hi, I update anaconda-mode to 0.1.12 .  It works normally.
I'm very sorry for taking up your time. 😊

**Comment by proofit404** [comment]
No problem
