### ISSUE TITLE
anaconda-mode with TRAMP not working?

### ISSUE THREAD

**Issue by falloutphil** [proofit404/anaconda-mode#335]
Hi,

I have latest anaconda-mode package (updated via packages-list-packages U x) installed on Emacs 26.1, using Ubuntu18.04.

When browsing local source anaconda-mode works as great, for look-ups, completions, etc.

When browsing to a remote file using TRAMP, nothing seems to work.

As per advice I am using IP address (not alias) to connect via ssh, I load the file up and attempt an M-. to find the definition of a function declared locally in that file.

The first time I try this I get the following message in the mini-buffer:

error in process filter: Wrong type argument: numberp, nil

Subsequent attempts get no further messages.

\*anaconda-mode\* contains only a single
anaconda_mode port 38317    

No subsequent messages occur.

Any ideas?

**Comment by proofit404** [comment]
Please describe how you configure python executable in Emacs for remote host.

**Comment by falloutphil** [comment]
Hi,

Thanks for reply.

In addition to the above I have noticed an *anaconda-response* buffer seems to be created:

> # status: (:error (error connection-failed deleted
>  :host 100.200.300.400 :service 38317) :error (error connection-failed failed with code 110
>  :host 100.200.300.400 :service 38317))
> # point: 1

Where 100.200.300.400 is the IP address of the _remote_ server (assuming emacs is running on a local server).

 I configure the Python executable as follows:
> python-shell-interpreter is a variable defined in ‘python.el’.
> Its value is "ipython3"
> Original value was "python"

I have also tried just "python3", but "ipython" seems to work when look at local files:

```
(require 'python)
(setq python-shell-interpreter "ipython3")
(setq python-shell-interpreter-args "--simple-prompt")
```

Having seen the new response header, I suspect the issue may be that the local instance of emacs is trying to contact the remote server over port 38317, rather than tunnelling all traffic down the TRAMP created ssh connection?  
If that is the case then firewall settings blocking incomming traffic on all non-standard ports may be the issues.

I can think of a few ways around this - is it possible to hardcode the port that is used by anconda?

I can either request that port is open, or more likely, will have to tunnel the traffic through an SSH tunnel using a local SOCKS proxy to the remote machine.

Thanks again!

**Comment by falloutphil** [comment]
I can get this working by replacing the following line anaconda-mode.el:

`service_factory.service_factory(app, server_address, 0, 'anaconda_mode port {port}')
" "Run `anaconda-mode' server.")`

With:

`service_factory.service_factory(app, server_address, 12345, 'anaconda_mode port {port}')
" "Run `anaconda-mode' server.")`

This keeps the port number of the RPCs constant.

I then create to port forwards on the server running emacs.  The first one forwards the RPCs, the second is to "fool" TRAMP into thinking our development is on localhost.

`
ssh -nNT -L 12345:localhost:12345 my-dev-server &
ssh -nNt -L 12346:localhost:22 my-dev-server &
`

You can then connect using `C-x d RET /ssh:user@localhost#12345:/path/to/dev` and it works.

However it's limited to a single server and it's pretty ugly!

Any better suggestions?

**Comment by AlexLewandowski** [comment]
I am also having this issue with a server I use at my university. However, I do not encounter this issue with my desktop (where I have extensively used tramp and anaconda-mode with no problem)

**Comment by termlen0** [comment]
Same here. This used to work a few versions ago

**Comment by falloutphil** [comment]
Just to confirm

> I can either request that port is open...

With the port fixed in the service_factory, and the opening of that port in the firewall settings, everything works as you'd expect, providing, as mentioned by @termlen0 you use the actual IP address, and not an ssh alias.

As a feature request it would be great to support ssh aliases (as per .ssh/config file).  Also if it was possible to provide tunnelling via port 22 as per my example above in a more elegant way, this would save the need for us to pester sysadmins, etc, to open up ports to allow the IDE to work - in some environments this is just not possible.

**Comment by falloutphil** [comment]
I've finally had some time to look at this properly.

In the below - I've either totally missed the point of the original code (in which case apologies for the time I'm about to waste!) - or I've found 3 bugs that I have fixed, and now there are not complications using anaconda-mode through a firewall.  Note also that AFAICS without doing the below fix the RPC calls are not secured, so if done across public networks release a limited amount of data to anyone who cares to sniff the http packets (the files always go over Tramp, but the look-up requests are insecure).

I've forked anaconda-mode and fixed here:
https://github.com/falloutphil/anaconda-mode/commit/2a64bc14365b6494a1725945df1bb66b0dbe769d

The fix does 2 things.
1. Prevents the nil/numberp type error on using tramp on default port 22 with ssh.
2. Creates a tunnel co-located with the client at localhost, and pipes traffic to the tramp location correctly.
3. Send the RPC requests to the tunnel not the remote tramp server

I suspect in both cases the original code was supposed to do this, but didn't allow for:
1. the pythonic port returning nil when not explicitly set
2. the port forward syntax did not bind to a local address on the client (instead using a remote address which will always fail)

Freakishly, everything still worked *if* you didn't have firewalls setup blocking the ports created by the RPC service, because the RPC requests were not forwarded to the (broken) tunnel, instead making a direct HTTP request to the Tramp server.  Albeit without the tunnel no security existed on the RPC calls.  This in itself is a bug (I think!) and in combination with 1 and 2 above actually made remote look-up work for the wrong reasons.

This explains why my various workarounds above did work - but should be avoided as of now  You should never need to open-up any port beyond that which Tramp already uses (e.g. 22) to make the proposed solution work.  In fact you shouldn't even set the port to a constant as I originally suggested.  Nor, should you manually create tunnels.

One tiny fly in the ointment - the first look-up after start-up of the tunnel will typically fail.  No doubt this is a race condition between the tunnel and the first RPC request.  However subsequent requests so far work fine with me.

I'm also able to use this with my other suggestion to tear-down and restart the tunnel when flipping from on server to another.

Feel free to pull my change into the original master - assuming you agree with what I've done, or if you want to discuss further just respond.

**Comment by AlexLewandowski** [comment]
This works very well for one of the servers at my university. However, it doesn't seem to work with "multi-hops", is that an easy fix? I assume you would have to tunnel one more time for each additional hop. But I don't know how you would tell if a multi-hop is occurring.

**Comment by AlexLewandowski** [comment]
Your solution works very well on one of the servers at my university. However, it doesn't seem to work with "multi-hop". Is that an easy fix? I imagine you need an extra port forward step for each additional hop. I'm not sure how to tell the difference between a multi-hop and not in elisp though.

Note: Deleted my earlier post since I thought I had resolved the issue but was mistaken. With your solution, I am able to use other remotes for completion which is fine for my use case for now.

**Comment by falloutphil** [comment]
Thanks for the feedback @AlexLewandowski - you're right that currently the RPC Tunnel will not handle multiple hops.  The fix could certainly be extended to work for multihop.  To do this we'd need to parse the tamp expression into a list of (user, server) elements, with the final item being the destination server.  You'd then setup a single SSH Tunnel to the destination - user_n@server_n, but pass an extra param "-J user_1@server_1,user_2@server_2,user_3@server_3.....user_n-1@server@n-1" to setup a set of proxy jumps.  Note this will only work on fairly recent version of OpenSSH which supports "-J".  Doing it without this is surely possible, but will be more complicated.  I don't have a use case for this at the moment, but agree it's useful - so if my original change is accepted, I can put this enhancement on my (fairly long!) todo list.

**Comment by falloutphil** [comment]
I was curious so I've made anaconda-mode multihop-compatible as per discussion with @AlexLewandowski  - you need to take all commits up to the below from my fork:
https://github.com/falloutphil/anaconda-mode/commit/a1a56aeb8e4de8a4c0600f6c8b5e0b2046fa5e50

The code is not particularly beautiful - but it works well for me.   The function `anaconda-jump-proxy-string` should perhaps be moved to the `pythonic` library.  It elaborates on the idea above.

A few notes on use:
* Tested using OpenSSH_7.6p1 and Emacs 26.1 - with 0 (both local and remote), 1, and 2 hops.  Should work with any number of hops.
* It requires a fairly recent version of OpenSSH client supporting "-J" or "ProxyJump" option.
* Before using it you need to make sure that any proxy'd connection is already in your know hosts - the easiest way to do this is to manually run "ssh -J p1,p2,p3 host" once from the command-line before first use of a certain proxy'd connection, and accept the connection so your known_hosts file is updated.  After that it will work as normal from within Emacs. 
* I've also added a 2 seconds sleep after setting up the tunnel to avoid the race condition - not that if you do several hops this might not be enough and so the first look-up may fail as with the original single hop version I wrote.  You can easily tweak it in the code to suit your needs.

**Comment by AlexLewandowski** [comment]
Damn, that works great! Thank you so much

**Comment by termlen0** [comment]
@falloutphil Will you be submitting a PR for this? Would love to be able to use this from melpa eventually.

**Comment by falloutphil** [comment]
Yes - I can do.  I'll do a little more tidy-up beforehand.  This will represent no functional change to the feature, but make the code a little more readable.  I guess the only question is if the function I've written should exist in `anaconda-mode` or `pythonic` library.  For simplicity I could leave it where it is, but it'll be up to the PR approvers (@proofit404 I guess) to decide if it's the right place for it.  If anyone has a strong opinion, if you voice it here, I'll see if I can update the code before submitting the PR.  It would be trivial enough move `anaconda-jump-proxy-string` to `pythonic-jump-proxy-string`, I don't think it requires any changes - however this would create a release dependency any future `anaconda-mode`, so this would need to be managed by the package owners.  If I hear nothing back I'll just submit a PR for `anaconda-mode`.  The function can always be moved in a later refactor, of course.

**Comment by NightMachinary** [comment]
When using `scp`, I got `Cannot read anaconda-mode server response`, and when I switched to `ssh`, I get:
```
anaconda_mode port 38787
127.0.0.1 - - [24/Mar/2021 14:14:35] ================================================================================
Traceback (most recent call last):
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "<string>", line 99, in wrapper
TypeError: __init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "TypeError(\'__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given\')"}}')
127.0.0.1 - - [24/Mar/2021 14:14:37] ================================================================================
Traceback (most recent call last):
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "<string>", line 99, in wrapper
TypeError: __init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "TypeError(\'__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given\')"}}')
127.0.0.1 - - [24/Mar/2021 14:14:37] ================================================================================
Traceback (most recent call last):
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "<string>", line 99, in wrapper
TypeError: __init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "TypeError(\'__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given\')"}}')
127.0.0.1 - - [24/Mar/2021 14:14:38] ================================================================================
Traceback (most recent call last):
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "<string>", line 99, in wrapper
TypeError: __init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "TypeError(\'__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given\')"}}')
127.0.0.1 - - [24/Mar/2021 14:14:40] ================================================================================
Traceback (most recent call last):
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "<string>", line 99, in wrapper
TypeError: __init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "TypeError(\'__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given\')"}}')
127.0.0.1 - - [24/Mar/2021 14:14:40] ================================================================================
Traceback (most recent call last):
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "<string>", line 99, in wrapper
TypeError: __init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "TypeError(\'__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given\')"}}')
127.0.0.1 - - [24/Mar/2021 14:14:50] ================================================================================
Traceback (most recent call last):
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "<string>", line 99, in wrapper
TypeError: __init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "TypeError(\'__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given\')"}}')
127.0.0.1 - - [24/Mar/2021 14:14:54] ================================================================================
Traceback (most recent call last):
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "<string>", line 99, in wrapper
TypeError: __init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "TypeError(\'__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given\')"}}')
127.0.0.1 - - [24/Mar/2021 14:14:55] ================================================================================
Traceback (most recent call last):
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "<string>", line 99, in wrapper
TypeError: __init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "TypeError(\'__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given\')"}}')
127.0.0.1 - - [24/Mar/2021 14:14:56] ================================================================================
Traceback (most recent call last):
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "<string>", line 99, in wrapper
TypeError: __init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "TypeError(\'__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given\')"}}')
127.0.0.1 - - [24/Mar/2021 14:14:57] ================================================================================
Traceback (most recent call last):
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "<string>", line 99, in wrapper
TypeError: __init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "TypeError(\'__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given\')"}}')
127.0.0.1 - - [24/Mar/2021 14:14:57] ================================================================================
Traceback (most recent call last):
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "<string>", line 99, in wrapper
TypeError: __init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/eva/.emacs.d.doom/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "TypeError(\'__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given\')"}}')
```

**Comment by dakra** [comment]
You should update anaconda-mode.

From the stacktrace it looks like you're using `0.1.13` and in `0.1.14` is a bugfix for newer jedi versions that match your error.

**Comment by NightMachinary** [comment]
[**@dakra**](https://github.com/dakra) commented on [Mar 24, 2021, 3:11 PM GMT+4:30](https://github.com/pythonic-emacs/anaconda-mode/issues/335#issuecomment-805707820 "2021-03-24T10:41:33Z - Replied by Github Reply Comments"):
> You should update anaconda-mode.
> 
> From the stacktrace it looks like you're using `0.1.13` and in `0.1.14` is a bugfix for newer jedi versions that match your error.

After updating to `(package! anaconda-mode :pin "344727c9e07e108896740c782689bf3588edcce5")
` (via doom), tramp keeps opening a new remote connection whenever it tries to use some anaconda-mode functionality, which happens all the time when eldoc is enabled. This is way worse than what I previously had with `Cannot read anaconda-mode server response`. Any way I can disable eldoc on remote Python buffers?

This is a known [issue](https://github.com/syl20bnr/spacemacs/issues/11514), but it is somehow on Spacemacs instead of here.

What is annoying is that this happens even when using `scp` ...

**Comment by falloutphil** [comment]
I think the best thing to do is to open a new ticket for this.  The above ticket was about fixing TRAMP tunneling via SSH, and enabling multihop connections to allow Jedi to proxy through a chain of servers.  The ticket achieved this aim and should remain closed - unless there is a problem specifically with multihop or tunneling.

It's over a year since I last looked at anaconda-mode's code so I'm not 100% up-to-speed, but I've offered some thoughts below.

The @NightMachinary  issue seems to be one of network performance.  And the solution would seem to be to reconfigure eldoc.

Could you reproduce the issue in vanilla emacs (to prove it's not a spacemacs issue) and go through step-by-step what is required to do this starting from an empty emacs config, and adding anaconda-mode (in the new ticket).

Anyway at the risk of being wrong a few wild guesses below!

* Anaconda mode does make Jedi RPC calls for every look-up - this is by design and wasn't changed by this #335 ticket (actually the RPC calls failed beforehand if there was any sort of firewall between local and remote machine - this was a bug).  However, if your connection is slow this can become quickly unusable - in hindsight the original idea to use over TRAMP was a little ambitious IMHO.  I only use TRAMP with Anaconda when I have a very fast/responsive connection and even then I don't use it in combination with other plugins that might add further burden on it.  In this case method look-ups work well.  Certainly using it across remote sites is tedious at best - I wouldn't recommend.
* Reverting #335 would reintroduce this bug which effects many users.  I accept in a totally crazy way it might improve performance because RPC fails quicker than it succeeds - but breaking a working feature that can be slow so that it fails in an uncontrolled manner (but quickly) isn't a very good idea at all (it also has security issues too).
* "Any way I can disable eldoc on remote Python buffers?"  --- It sounds like the feature you're asking for should be raised on eldoc not anaconda-mode?
* Also along the same lines - to reign in the performance issues, a new feature could be requested on anaconda-mode to turn off RPC in TRAMP, but this is not a bug, it would be a new feature.  What aspects of anaconda-mode would then remain turned-on in TRAMP that would remain useful without RPC - I'm wondering if the easiest thing is for you to just have a hook that disables anaconda-mode altogether when accessing a python file via TRAMP?
* If the problem is specifically with SSH - I'd suggest using ControlMaster config to hold the tunnel open between sessions - but I don't think this is the issue here.  This does speed-up tunnel creation, not each RPC call through the tunnel.

Hope this helps clarify things a bit!

**Comment by NightMachinary** [comment]
@falloutphil You're right. I opened a new [issue](https://github.com/pythonic-emacs/anaconda-mode/issues/413).
