### ISSUE TITLE
Adding libraries

### ISSUE THREAD

**Issue by silgon** [proofit404/anaconda-mode#36]
One little question. I'm using company-anaconda mode. And I'm getting some completions really good.
For example for:

```
import numpy as np
np.
```

After the `.` I'm getting good completions. But with some other libraries I don't. I'm sure that it's because of the libraries being loaded and the default paths. How can I add more paths for this usage?
Or is it a company-anaconda question?

**Comment by silgon** [comment]
I wouldn't like to reopen this issue but just one thing, I updated this package, I was using before the git version (outdated from one year ago) and now I went for the MELPA packages in order to have everything nicely synchronized. But apparently, the libraries from the directory `PYTHONPATH` are not being imported.

Anyway, let's say I have this code.

```python
import tf
tf.  # error is generated after the point and/or with the command company-complete
```

The `tf` library is imported from `PYTHONPATH` and it should autocomplete (as before). Nonetheless the error I get is the following.

```
Company: Back-end company-anaconda error "JSON-RPC error condition: :data, "AttributeError(\"'NoneType' object has no attribute 'names_dict'\",)", :code, -32000, :message, "Server error"" with args (candidates )
```

Any ideas? Thanks in advance =)

Side note: if I use `ipython` and press tab, I can see the completion options (just to check that the `PYTHONPATH` variable is ok.

**Comment by proofit404** [comment]
Looks like a problem with jedi 0.9 library. I need `*anaconda-mode*` buffer content for more info. Try to downgrade jedi library (within Emacs):
```
M-x find-library RET anaconda-mode RET
M-! rm -rf jedi* RET
M-! pip install "jedi<0.9" -t . RET
```

**Comment by silgon** [comment]
I downgraded jedi with `pip install "jedi<0.9"` which installed `jedi (0.8.1-final0)`. Nonetheless I have the same error. Here is the `*anaconda-mode*` buffer content.

```
127.0.0.1 - - [28/May/2015 19:04:46] ================================================================================
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/usr/local/lib/python2.7/dist-packages/service_factory/service.py", line 49, in __call__
    result = self.apply(method, args)
  File "/usr/local/lib/python2.7/dist-packages/service_factory/service.py", line 104, in apply
    server_error(args['id'], error)
  File "/usr/local/lib/python2.7/dist-packages/service_factory/errors.py", line 92, in server_error
    six.raise_from(ServiceException(500, dumps(response)), error)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 692, in raise_from
    raise value
ServiceException: (500, '{"jsonrpc": "2.0", "id": 6, "error": {"message": "Server error", "code": -32000, "data": "AttributeError(\\"\'NoneType\' object has no attribute \'names_dict\'\\",)"}}')

Process anaconda_mode killed
Python executable: /usr/bin/python
jedi version: 0.8.1-final0
service_factory version: 0.1.2
anaconda_mode port 9000
```

**Comment by proofit404** [comment]
Why version uprears after actual stack trace? Can you try with fresh emacs session?

**Comment by silgon** [comment]
Oops, Sorry, I didn't know the order. I send you the information with both versions. Both taken wich a fresh emacs session each.

```
Python executable: /usr/bin/python
jedi version: 0.9.0
service_factory version: 0.1.2
anaconda_mode port 9000
127.0.0.1 - - [29/May/2015 12:06:17] ================================================================================
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/usr/local/lib/python2.7/dist-packages/service_factory/service.py", line 49, in __call__
    result = self.apply(method, args)
  File "/usr/local/lib/python2.7/dist-packages/service_factory/service.py", line 104, in apply
    server_error(args['id'], error)
  File "/usr/local/lib/python2.7/dist-packages/service_factory/errors.py", line 92, in server_error
    six.raise_from(ServiceException(500, dumps(response)), error)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 692, in raise_from
    raise value
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "AttributeError(\\"\'NoneType\' object has no attribute \'names_dict\'\\",)"}}')
```

```
Python executable: /usr/bin/python
jedi version: 0.8.1-final0
service_factory version: 0.1.2
anaconda_mode port 9000
127.0.0.1 - - [29/May/2015 12:08:49] ================================================================================
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/usr/local/lib/python2.7/dist-packages/service_factory/service.py", line 49, in __call__
    result = self.apply(method, args)
  File "/usr/local/lib/python2.7/dist-packages/service_factory/service.py", line 104, in apply
    server_error(args['id'], error)
  File "/usr/local/lib/python2.7/dist-packages/service_factory/errors.py", line 92, in server_error
    six.raise_from(ServiceException(500, dumps(response)), error)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 692, in raise_from
    raise value
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "ImportError(\'libtf2_ros.so: cannot open shared object file: No such file or directory\',)"}}')
```

**Comment by proofit404** [comment]
Second trace back is the most interesting however. As you can see there is some import problem in it. What installation method are you use for python packages? Can you provide `pip freeze` info?

**Comment by silgon** [comment]
My installation method is `pip install <package-name` and I do it as root. For virtualenv purposes I use anaconda, but that's not the problem right now, since I'm not testing with it. `pip freeze` only gives me the list of packages installed like `jedi==0.9.0`. I can sent it but the list is quite big.
