### ISSUE TITLE
Error choosing Python interpreter

### ISSUE THREAD

**Issue by matthieucan** [proofit404/anaconda-mode#363]
Hi,
I've set up python3 as my python interpreter:
```
(setq python-shell-interpreter "python3")
```

However it seems anaconda-mode is executed using python2. I get in the anaconda buffer:
```
Traceback (most recent call last):
  File "<string>", line 59, in <module>
  File "<string>", line 49, in install_deps
ImportError: No module named setuptools.command.easy_install
```

This import works with python3, but not with python2, hence I suspect my choice of interpreter is not honored.

What can I do?

For info, I'm using spacemacs on Linux.

**Comment by CeleritasCelery** [comment]
first, check the value of `pythonic-interpreter` and make sure that is pointing to `python3` as well. If that is true, check that `(executable-find "python3")` is pointing to the same location as `which python3` in your shell.
