### ISSUE TITLE
Blocking call to accept-process-output with quit inhibited

### ISSUE THREAD

**Issue by nlamirault** [proofit404/anaconda-mode#64]
i've got this error message : 

***Blocking call to accept-process-output with quit inhibited***

In the *anaconda-mode* buffer : 

```python
Process anaconda_mode exited abnormally with code 1
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 11, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
Traceback (most recent call last):
  File "/home/vagrant/.emacs.d/.cask/25.0.50.1/elpa/anaconda-mode-20150127.125/anaconda_mode.py", line 43, in <module>
    assert pip.returncode is 0, 'PyPi installation fails.'
AssertionError: PyPi installation fails.

Process anaconda_mode exited abnormally with code 1
```

**Comment by proofit404** [comment]
Seems like it's a problem with your pip installation inside vagrant. Please try [this](http://stackoverflow.com/questions/27341064/how-do-i-fix-importerror-cannot-import-name-incompleteread/27341847#27341847).

**Comment by nlamirault** [comment]
OK. Thanks. With a recent version of pip it works fine.
