### ISSUE TITLE
Blocking call issue again with an OverFlowError

### ISSUE THREAD

**Issue by dsdshcym** [proofit404/anaconda-mode#70]
I have the blocking call issue again today.

Already tried reinstall jedi, json-rpc but no luck.

This is the content of the whole ```anaconda``` buffer:
https://gist.github.com/dsdshcym/06202ebb073c30f47d6b

**Comment by proofit404** [comment]
I think we can reproduce this error in more details with following code snippet
```python
from BaseHTTPServer import HTTPServer
from SimpleHTTPServer import SimpleHTTPRequestHandler
host = 'localhost'
port = 24970
server = HTTPServer((host, port), SimpleHTTPRequestHandler)
server.serve_forever()
```

**Comment by dsdshcym** [comment]
Yes, I ran this code.

First time, I got a Traceback:
```
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dsdshcym/Projects/tempCodes/temp.py", line 5, in <module>
    server = HTTPServer((host, port), SimpleHTTPRequestHandler)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 47] Address family not supported by protocol family
```

Then I modified ```port``` to 249700, I got this:
```
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dsdshcym/Projects/tempCodes/temp.py", line 5, in <module>
    server = HTTPServer((host, port), SimpleHTTPRequestHandler)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
OverflowError: getsockaddrarg: port must be 0-65535.
```

Could that provide any help?

**Comment by dsdshcym** [comment]
And I'm using spacemacs, which is using ```ac-anaconda``` and ```company-anaconda``` at the same time(I'm not sure about it though, but both packages are installed)

**Comment by proofit404** [comment]
Looks like you system prefer IPv6 for localhost interface.  You can try following steps

    M-x find-library RET anaconda_mode.py RET
    M-g M-g 185 RET

Replace `localhost` iface name with `127.0.0.1` safe buffer and restart you emacs.

**Comment by dsdshcym** [comment]
@proofit404 Yes, it seems everything is fine now.

Thanks a lot!

**Comment by proofit404** [comment]
Ok. I'll make same changes in the upstream.
