### ISSUE TITLE
anaconda-mode-goto pyqtSignal causes server error

### ISSUE THREAD

**Issue by pronobis** [proofit404/anaconda-mode#78]
When using `anaconda-mode-goto` on the following signal in PyQt (see | for cursor position)
```
        self.tree_widget = QtGui.QTreeWidget(self.main_widget)
        self.tree_widget.item|Changed.connect(self.category_checked)
```
I get the following error:
```
JSON-RPC error condition: :data, "AttributeError(\"'PyQt4.QtCore.pyqtSignal' object has no attribute '__name__'\",)", :code, -32000, :message, "Server error"
```
with *anaconda-mode* buffer:
```
Python executable: /home/user/.virtualenv/python3/bin/python
jedi version: 0.8.1-final0
service_factory version: 0.1.2
anaconda_mode port 9000 
127.0.0.1 - - [07/Apr/2015 21:02:31] ================================================================================
Traceback (most recent call last):
  File "/home/user/.virtualenv/python3/lib/python3.4/site-packages/jedi/cache.py", line 137, in wrapper
    return getattr(self, name)
AttributeError: 'Definition' object has no attribute '_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.emacs.d/elpa/anaconda-mode-20150313.655/service_factory/service.py", line 102, in apply
    result = method(*params)
  File "/home/user/.emacs.d/elpa/anaconda-mode-20150313.655/anaconda_mode.py", line 61, in wrapper
    return f(Script(source, line, column, path))
  File "/home/user/.emacs.d/elpa/anaconda-mode-20150313.655/anaconda_mode.py", line 116, in wrapper
    for d in f(script) if not d.in_builtin_module()]
  File "/home/user/.emacs.d/elpa/anaconda-mode-20150313.655/anaconda_mode.py", line 124, in goto_definitions
    return script.goto_definitions()
  File "/home/user/.virtualenv/python3/lib/python3.4/site-packages/jedi/api/__init__.py", line 398, in goto_definitions
    d = set([classes.Definition(self._evaluator, s) for s in definitions
  File "/home/user/.virtualenv/python3/lib/python3.4/site-packages/jedi/api/classes.py", line 678, in __hash__
    return hash((self._start_pos, self.module_path, self.name, self._evaluator))
  File "/home/user/.virtualenv/python3/lib/python3.4/site-packages/jedi/cache.py", line 139, in wrapper
    result = func(self)
  File "/home/user/.virtualenv/python3/lib/python3.4/site-packages/jedi/api/classes.py", line 560, in name
    name = d.name
  File "/home/user/.virtualenv/python3/lib/python3.4/site-packages/jedi/evaluate/compiled/__init__.py", line 149, in name
    return self._cls().obj.__name__
AttributeError: 'PyQt4.QtCore.pyqtSignal' object has no attribute '__name__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.emacs.d/elpa/anaconda-mode-20150313.655/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/user/.emacs.d/elpa/anaconda-mode-20150313.655/service_factory/service.py", line 49, in __call__
    result = self.apply(method, args)
  File "/home/user/.emacs.d/elpa/anaconda-mode-20150313.655/service_factory/service.py", line 104, in apply
    server_error(args['id'], error)
  File "/home/user/.emacs.d/elpa/anaconda-mode-20150313.655/service_factory/errors.py", line 92, in server_error
    six.raise_from(ServiceException(500, dumps(response)), error)
  File "<string>", line 2, in raise_from
service_factory.exceptions.ServiceException: (500, '{"id": 1, "jsonrpc": "2.0", "error": {"message": "Server error", "code": -32000, "data": "AttributeError(\\"\'PyQt4.QtCore.pyqtSignal\' object has no attribute \'__name__\'\\",)"}}')
```

**Comment by proofit404** [comment]
That seems like a jedi bug.  Can you try following:

```python
from jedi import Script
code = """<your buffer content here>"""
script = Script(code, <your_line_number>, <your_column_number>, <your_file_path>)
script.goto_definitions()
```

**Comment by pronobis** [comment]
Indeed:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/jedi/cache.py", line 137, in wrapper
    return getattr(self, name)
AttributeError: 'Definition' object has no attribute '_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 94, in <module>
    script.goto_definitions()
  File "/usr/local/lib/python3.4/dist-packages/jedi/api/__init__.py", line 398, in goto_definitions
    d = set([classes.Definition(self._evaluator, s) for s in definitions
  File "/usr/local/lib/python3.4/dist-packages/jedi/api/classes.py", line 678, in __hash__
    return hash((self._start_pos, self.module_path, self.name, self._evaluator))
  File "/usr/local/lib/python3.4/dist-packages/jedi/cache.py", line 139, in wrapper
    result = func(self)
  File "/usr/local/lib/python3.4/dist-packages/jedi/api/classes.py", line 560, in name
    name = d.name
  File "/usr/local/lib/python3.4/dist-packages/jedi/evaluate/compiled/__init__.py", line 149, in name
    return self._cls().obj.__name__
AttributeError: 'PyQt4.QtCore.pyqtSignal' object has no attribute '__name__'
```

Indeed. Should that be reported as a Jedi issue?

**Comment by proofit404** [comment]
Absolutely! Since this isn't related to my package I'll close that one.
