### ISSUE TITLE
JSON-RPC error condition

### ISSUE THREAD

**Issue by mandarm** [proofit404/anaconda-mode#85]
I periodically get these messages when editing a .py file. Have I setup something incorrectly? Thanks very much!

Company: An error occurred in auto-begin
Company: Back-end company-anaconda error "JSON-RPC error condition: :data, "AttributeError(\"'Completion' object has no attribute 'docstring'\",)", :code, -32000, :message, "Server error"" with args (candidates ran)

My *anaconda-mode* buffer looks like this:

Python executable: /home/mandar/Dropbox/python/.python-environments/default/bin/python
jedi version: 0.7.0
service_factory version: 0.1.2
anaconda_mode port 9000
127.0.0.1 - - [07/May/2015 23:22:51] ================================================================================
Traceback (most recent call last):
  File "/home/mandar/.local/lib/python2.7/site-packages/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/mandar/.local/lib/python2.7/site-packages/service_factory/service.py", line 49, in __call__
    result = self.apply(method, args)
  File "/home/mandar/.local/lib/python2.7/site-packages/service_factory/service.py", line 104, in apply
    server_error(args['id'], error)
  File "/home/mandar/.local/lib/python2.7/site-packages/service_factory/errors.py", line 92, in server_error
    six.raise_from(ServiceException(500, dumps(response)), error)
  File "/home/mandar/.local/lib/python2.7/site-packages/six.py", line 692, in raise_from
    raise value
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "AttributeError(\\"\'Completion\' object has no attribute \'docstring\'\\",)"}}')

**Comment by proofit404** [comment]
Try to update `jedi` to `0.9.0`

**Comment by mandarm** [comment]
Yes, I think this fixed the problem. Thank you very much!

**Comment by proofit404** [comment]
You're welcome.
