### ISSUE TITLE
JSON-RPC error when using jedi 0.9

### ISSUE THREAD

**Issue by cobbled** [proofit404/anaconda-mode#88]
python code:

```python
import requests
result = requests.get('http://www.gnu.org/')
result.
```

Each time I hit ```C-M-i``` after ```result.```, I got this error in the mini buffer:

```JSON-RPC error condition: :data, "AttributeError(\"'ListComprehension' object has no attribute 'parent'\",)", :code, -32000, :message, "Server error"```

```*anaconda-mode*``` buffer content:

```log
Python executable: /home/cobbled/.pyenv/versions/2.7.9/bin/python
jedi version: 0.9.0
service_factory version: 0.1.2
anaconda_mode port 9000
127.0.0.1 - - [22/May/2015 14:47:04] ================================================================================
Traceback (most recent call last):
  File "/home/cobbled/.emacs.d/elpa/anaconda-mode-20150313.655/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/cobbled/.emacs.d/elpa/anaconda-mode-20150313.655/service_factory/service.py", line 49, in __call__
    result = self.apply(method, args)
  File "/home/cobbled/.emacs.d/elpa/anaconda-mode-20150313.655/service_factory/service.py", line 104, in apply
    server_error(args['id'], error)
  File "/home/cobbled/.emacs.d/elpa/anaconda-mode-20150313.655/service_factory/errors.py", line 92, in server_error
    six.raise_from(ServiceException(500, dumps(response)), error)
  File "/home/cobbled/.emacs.d/elpa/anaconda-mode-20150313.655/six.py", line 692, in raise_from
    raise value
ServiceException: (500, '{"jsonrpc": "2.0", "id": 2, "error": {"message": "Server error", "code": -32000, "data": "AttributeError(\\"\'ListComprehension\' object has no attribute \'parent\'\\",)"}}')
127.0.0.1 - - [22/May/2015 14:47:04] ================================================================================
Traceback (most recent call last):
  File "/home/cobbled/.emacs.d/elpa/anaconda-mode-20150313.655/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/cobbled/.emacs.d/elpa/anaconda-mode-20150313.655/service_factory/service.py", line 49, in __call__
    result = self.apply(method, args)
  File "/home/cobbled/.emacs.d/elpa/anaconda-mode-20150313.655/service_factory/service.py", line 104, in apply
    server_error(args['id'], error)
  File "/home/cobbled/.emacs.d/elpa/anaconda-mode-20150313.655/service_factory/errors.py", line 92, in server_error
    six.raise_from(ServiceException(500, dumps(response)), error)
  File "/home/cobbled/.emacs.d/elpa/anaconda-mode-20150313.655/six.py", line 692, in raise_from
    raise value
ServiceException: (500, '{"jsonrpc": "2.0", "id": 3, "error": {"message": "Server error", "code": -32000, "data": "AttributeError(\\"\'ListComprehension\' object has no attribute \'parent\'\\",)"}}')
127.0.0.1 - - [22/May/2015 14:47:04] ================================================================================
Traceback (most recent call last):
  File "/home/cobbled/.emacs.d/elpa/anaconda-mode-20150313.655/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/cobbled/.emacs.d/elpa/anaconda-mode-20150313.655/service_factory/service.py", line 49, in __call__
    result = self.apply(method, args)
  File "/home/cobbled/.emacs.d/elpa/anaconda-mode-20150313.655/service_factory/service.py", line 104, in apply
    server_error(args['id'], error)
  File "/home/cobbled/.emacs.d/elpa/anaconda-mode-20150313.655/service_factory/errors.py", line 92, in server_error
    six.raise_from(ServiceException(500, dumps(response)), error)
  File "/home/cobbled/.emacs.d/elpa/anaconda-mode-20150313.655/six.py", line 692, in raise_from
    raise value
ServiceException: (500, '{"jsonrpc": "2.0", "id": 4, "error": {"message": "Server error", "code": -32000, "data": "AttributeError(\\"\'ListComprehension\' object has no attribute \'parent\'\\",)"}}')
```

After I switch back to 0.8.1 version of jedi, this error does not appear angain.

**Comment by proofit404** [comment]
This is a jedi bug: https://github.com/davidhalter/jedi/issues/592
Thanks for report!

**Comment by geo7** [comment]
Code : 

```python
#! /usr/bin/python3.4

import requests
import bs4

res = requests.get('http://google.com/search?q={}'.format(sys.argv[1:]))
res.<error comes up here> 
```

Error : 

http://i.imgur.com/gPeRXst.png

This occurs with the above code after typing `res.`, 


from here : https://github.com/syl20bnr/spacemacs/issues/1973

**Comment by proofit404** [comment]
@geo7 Does rollback to the `0.8` fix your problem?

**Comment by geo7** [comment]
@proofit404 hey, I'm sorry but I'm not too sure how to roll back and stuff, it's probably easier for me to just put up with the error. I posted because I thought maybe it'd be useful info or something. If you want any more info / logs I'm happy to post though.

**Comment by proofit404** [comment]
Sorry for too quick reply without details. This is how you can rollback `jedi` library: https://github.com/proofit404/anaconda-mode/issues/36#issuecomment-106574023
